namespace tsl {

// test functions based on tsl-7Liin7LiD-mixed.endf
namespace li7inli7d {

  void verifyDocumentation( const Documentation& documentation ) {

    std::string description =
      " 7Li(7LiD) NNL        EVAL-MAR23 Zerkle, Holmes, Wormald          \n"
      " Ref. 1               DIST-AUG24 REV1-MAY24            20240830   \n"
      "---- ENDF/B-VIII.1    MATERIAL 3034         REVISION 1            \n"
      "----- THERMAL NEUTRON SCATTERING DATA                             \n"
      "------ ENDF-6                                                     \n"
      "                                                                  \n"
      "  Temperatures = 293.6 400 500 600 700 800 K                      \n"
      "                                                                  \n"
      " HISTORY                                                          \n"
      " -------                                                          \n"
      " This evaluation was generated by Naval Nuclear Laboratory (Mar   \n"
      " 2023) [1] using the FLASSH code [2].  The physical model is      \n"
      " based on the mixed elastic scattering treatment and includes     \n"
      " coherent elastic scattering, incoherent elastic scattering and   \n"
      " inelastic scattering contributions. This evaluation is intended  \n"
      " to be used with the companion D(7LiD) TSL evaluation when        \n"
      " modeling enriched 7LiD.                                          \n"
      "                                                                  \n"
      " THEORY                                                           \n"
      " ------                                                           \n"
      " Lithium hydride (LiD) has a fluorite (NaCl) type face-centered   \n"
      " cubic crystal structure with four Li and D atoms per unit call.  \n"
      " The inelastic scattering cross sections were calculated in the   \n"
      " incoherent approximation using the Li-7 partial phonon density   \n"
      " of states from a VASP/PHONON calculation of 7LiD based on the    \n"
      " crystal structure and lattice constant from [3].  The mixed      \n"
      " elastic scattering treatment was used to account for both        \n"
      " coherent and incoherent elastic scattering effects present in    \n"
      " this material.  The coherent elastic scattering component was    \n"
      " calculated in the cubic approxiation using the FLASSH            \n"
      " generalized coherent elastic scattering module using the 7LiD    \n"
      " crystal structure and measured room temperature lattice          \n"
      " constant of 4.0684 Ang [3] along with free atom coherent         \n"
      " scattering cross sections of 0.51 b for Li-7 from [5] and 2.483  \n"
      " b for D from [4]. The incoherent elastic scattering component    \n"
      " was calculated using the Debye-Waller factor derived from the    \n"
      " Li-7 partial phonon density of states and a Li-7 free atom       \n"
      " incoherent scattering cross section of 0.46 b from [5].  A Li-7  \n"
      " free atom total scattering cross section of 0.97 b was used to   \n"
      " ensure consistency with the ENDF/B-VIII.1 Li-7 evaluation. A     \n"
      " phonon order of 500 was used to ensure both the inelastic        \n"
      " scattering cross section and the S(alpha,beta) functions at      \n"
      " elevated temperatures were adaquately converged.                 \n"
      "                                                                  \n"
      " REFERENCES                                                       \n"
      " ----------                                                       \n"
      " 1. M. L. Zerkle, personal communications, Mar 9, 2023.           \n"
      "                                                                  \n"
      " 2. A. I. Hawari, et. al, FLASSH.beta3.2 User Guide (2022).       \n"
      "                                                                  \n"
      " 3. V. F. Sears, Neutron News, 3, 2-37 (1992).                    \n"
      "                                                                  \n"
      " 4. S. F. Mughabghab, Atlas of Neutron Resonances, 5th Edition,   \n"
      "    Elsevier, Amsterdam (2006).                                   \n"
      "                                                                  \n"
      " -----------------------------------------------------------------\n";

    CHECK( 0 == documentation.library() );
    CHECK( std::make_pair( 8, 1 ) == documentation.version() );
    CHECK( description == documentation.description() );
  }

  void verifyCoherentElastic( const std::optional< njoy::dryad::thermal::CoherentElasticScattering >& elastic ) {

    CHECK( std::nullopt != elastic );

    CHECK( 6 == elastic->numberModeratorTemperatures() );
    CHECK_THAT( 293.6, WithinRel( elastic->braggEdges()[0].temperature() ) );
    CHECK_THAT( 400. , WithinRel( elastic->braggEdges()[1].temperature() ) );
    CHECK_THAT( 700. , WithinRel( elastic->braggEdges()[4].temperature() ) );
    CHECK_THAT( 800. , WithinRel( elastic->braggEdges()[5].temperature() ) );
    CHECK( 112 == elastic->braggEdges()[0].numberBraggEdges() );
    CHECK( 112 == elastic->braggEdges()[1].numberBraggEdges() );
    CHECK( 112 == elastic->braggEdges()[4].numberBraggEdges() );
    CHECK( 112 == elastic->braggEdges()[5].numberBraggEdges() );
    CHECK( 112 == elastic->braggEdges()[0].energies().size() );
    CHECK( 112 == elastic->braggEdges()[1].energies().size() );
    CHECK( 112 == elastic->braggEdges()[4].energies().size() );
    CHECK( 112 == elastic->braggEdges()[5].energies().size() );
    CHECK( 112 == elastic->braggEdges()[0].values().size() );
    CHECK( 112 == elastic->braggEdges()[1].values().size() );
    CHECK( 112 == elastic->braggEdges()[4].values().size() );
    CHECK( 112 == elastic->braggEdges()[5].values().size() );

    CHECK_THAT( 3.706719e-3, WithinRel( elastic->braggEdges()[0].energies().front() ) );
    CHECK_THAT( 3.706719e-3, WithinRel( elastic->braggEdges()[1].energies().front() ) );
    CHECK_THAT( 3.706719e-3, WithinRel( elastic->braggEdges()[4].energies().front() ) );
    CHECK_THAT( 3.706719e-3, WithinRel( elastic->braggEdges()[5].energies().front() ) );
    CHECK_THAT( 5., WithinRel( elastic->braggEdges()[0].energies().back() ) );
    CHECK_THAT( 5., WithinRel( elastic->braggEdges()[1].energies().back() ) );
    CHECK_THAT( 5., WithinRel( elastic->braggEdges()[4].energies().back() ) );
    CHECK_THAT( 5., WithinRel( elastic->braggEdges()[5].energies().back() ) );

    CHECK_THAT( 3.757353e-3, WithinRel( elastic->braggEdges()[0].values().front() ) );
    CHECK_THAT( 3.686081e-3, WithinRel( elastic->braggEdges()[1].values().front() ) );
    CHECK_THAT( 3.428755e-3, WithinRel( elastic->braggEdges()[4].values().front() ) );
    CHECK_THAT( 3.337757e-3, WithinRel( elastic->braggEdges()[5].values().front() ) );
    CHECK_THAT( 8.406348e-2, WithinRel( elastic->braggEdges()[0].values().back() ) );
    CHECK_THAT( 6.996602e-2, WithinRel( elastic->braggEdges()[1].values().back() ) );
    CHECK_THAT( 4.402291e-2, WithinRel( elastic->braggEdges()[4].values().back() ) );
    CHECK_THAT( 3.861519e-2, WithinRel( elastic->braggEdges()[5].values().back() ) );
  }

  void verifyIncoherentElastic( const std::optional< njoy::dryad::thermal::IncoherentElasticScattering >& elastic ) {

    CHECK( std::nullopt != elastic );

    CHECK_THAT( 0.6017726, WithinRel( elastic->boundCrossSection() ) );
    CHECK( 6 == elastic->debyeWallerIntegral().temperatures().size() );
    CHECK( 6 == elastic->debyeWallerIntegral().values().size() );
    CHECK_THAT( 293.6, WithinRel( elastic->debyeWallerIntegral().temperatures()[0] ) );
    CHECK_THAT( 400. , WithinRel( elastic->debyeWallerIntegral().temperatures()[1] ) );
    CHECK_THAT( 700. , WithinRel( elastic->debyeWallerIntegral().temperatures()[4] ) );
    CHECK_THAT( 800. , WithinRel( elastic->debyeWallerIntegral().temperatures()[5] ) );
    CHECK_THAT( 7.074031, WithinRel( elastic->debyeWallerIntegral().values()[0] ) );
    CHECK_THAT( 9.081680, WithinRel( elastic->debyeWallerIntegral().values()[1] ) );
    CHECK_THAT( 15.10002, WithinRel( elastic->debyeWallerIntegral().values()[4] ) );
    CHECK_THAT( 17.15230, WithinRel( elastic->debyeWallerIntegral().values()[5] ) );
  }

  void verifyIncoherentInelastic( const std::optional< njoy::dryad::thermal::IncoherentInelasticScattering >& inelastic ) {

    CHECK( std::nullopt != inelastic );

    CHECK_THAT( 1e-5, WithinRel( inelastic->lowerEnergyLimit() ) );
    CHECK_THAT( 10. , WithinRel( inelastic->upperEnergyLimit() ) );
    CHECK_THAT( 0.97 * ( 6.955734 + 1. ) * ( 6.955734 + 1. ) / 6.955734 / 6.955734,
                WithinRel( inelastic->boundCrossSection() ) );

    CHECK( 6 == inelastic->numberModeratorTemperatures() );
    CHECK( 6 == inelastic->moderatorTemperatures().size() );
    CHECK_THAT(  293.6, WithinRel( inelastic->moderatorTemperatures()[0] ) );
    CHECK_THAT(  400  , WithinRel( inelastic->moderatorTemperatures()[1] ) );
    CHECK_THAT(  500  , WithinRel( inelastic->moderatorTemperatures()[2] ) );
    CHECK_THAT(  600  , WithinRel( inelastic->moderatorTemperatures()[3] ) );
    CHECK_THAT(  700  , WithinRel( inelastic->moderatorTemperatures()[4] ) );
    CHECK_THAT(  800  , WithinRel( inelastic->moderatorTemperatures()[5] ) );

    double min = std::numeric_limits< double >::min();

    auto sab = inelastic->scatteringKernel( 293.6 );
    CHECK_THAT( 293.6     , WithinRel( sab.moderatorTemperature() ) );
    CHECK_THAT( 359.1459, WithinRel( sab.effectiveTemperature() ) );
    CHECK( true == sab.isEnergyTransferSymmetric() );
    auto table = sab.tabulatedScatteringKernel();
    CHECK_THAT( 0.         , WithinRel( table.lowerEnergyTransferLimit() ) );
    CHECK_THAT( 1.976285e+2, WithinRel( table.upperEnergyTransferLimit() ) );
    CHECK_THAT( 5.625091e-3, WithinRel( table.lowerMomentumTransferLimit() ) );
    CHECK_THAT( 1.136492e+2, WithinRel( table.upperMomentumTransferLimit() ) );
    CHECK_THAT( 4.752472e-4, WithinRel( table( 5.625091e-3, 0. ) ) );
    CHECK_THAT( min        , WithinRel( table( 5.625091e-3, 1.976285e+2 ) ) );
    CHECK_THAT( 5.97347e-14, WithinRel( table( 1.136492e+2, 0. ) ) );
    CHECK_THAT( 2.98622e-50, WithinRel( table( 1.136492e+2, 1.976285e+2 ) ) );

    sab = inelastic->scatteringKernel( 400 );
    CHECK_THAT( 400     , WithinRel( sab.moderatorTemperature() ) );
    CHECK_THAT( 449.4184, WithinRel( sab.effectiveTemperature() ) );
    CHECK( true == sab.isEnergyTransferSymmetric() );
    table = sab.tabulatedScatteringKernel();
    CHECK_THAT( 0.         , WithinRel( table.lowerEnergyTransferLimit() ) );
    CHECK_THAT( 1.976285e+2, WithinRel( table.upperEnergyTransferLimit() ) );
    CHECK_THAT( 5.625091e-3, WithinRel( table.lowerMomentumTransferLimit() ) );
    CHECK_THAT( 1.136492e+2, WithinRel( table.upperMomentumTransferLimit() ) );
    CHECK_THAT( 8.849429e-4, WithinRel( table( 5.625091e-3, 0. ) ) );
    CHECK_THAT( min        , WithinRel( table( 5.625091e-3, 1.976285e+2 ) ) );
    CHECK_THAT( 5.27000e-11, WithinRel( table( 1.136492e+2, 0. ) ) );
    CHECK_THAT( 6.90772e-38, WithinRel( table( 1.136492e+2, 1.976285e+2 ) ) );

    sab = inelastic->scatteringKernel( 500 );
    CHECK_THAT( 500     , WithinRel( sab.moderatorTemperature() ) );
    CHECK_THAT( 540.0094, WithinRel( sab.effectiveTemperature() ) );
    CHECK( true == sab.isEnergyTransferSymmetric() );
    table = sab.tabulatedScatteringKernel();
    CHECK_THAT( 0.         , WithinRel( table.lowerEnergyTransferLimit() ) );
    CHECK_THAT( 1.976285e+2, WithinRel( table.upperEnergyTransferLimit() ) );
    CHECK_THAT( 5.625091e-3, WithinRel( table.lowerMomentumTransferLimit() ) );
    CHECK_THAT( 1.136492e+2, WithinRel( table.upperMomentumTransferLimit() ) );
    CHECK_THAT( 1.386550e-3, WithinRel( table( 5.625091e-3, 0. ) ) );
    CHECK_THAT( min        , WithinRel( table( 5.625091e-3, 1.976285e+2 ) ) );
    CHECK_THAT( 2.787189e-9, WithinRel( table( 1.136492e+2, 0. ) ) );
    CHECK_THAT( 6.59121e-31, WithinRel( table( 1.136492e+2, 1.976285e+2 ) , 1e-12) );

    sab = inelastic->scatteringKernel( 600 );
    CHECK_THAT( 600     , WithinRel( sab.moderatorTemperature() ) );
    CHECK_THAT( 633.5643, WithinRel( sab.effectiveTemperature() ) );
    CHECK( true == sab.isEnergyTransferSymmetric() );
    table = sab.tabulatedScatteringKernel();
    CHECK_THAT( 0.         , WithinRel( table.lowerEnergyTransferLimit() ) );
    CHECK_THAT( 1.976285e+2, WithinRel( table.upperEnergyTransferLimit() ) );
    CHECK_THAT( 5.625091e-3, WithinRel( table.lowerMomentumTransferLimit() ) );
    CHECK_THAT( 1.136492e+2, WithinRel( table.upperMomentumTransferLimit() ) );
    CHECK_THAT( 2.001883e-3, WithinRel( table( 5.625091e-3, 0. ) ) );
    CHECK_THAT( min        , WithinRel( table( 5.625091e-3, 1.976285e+2 ) ) );
    CHECK_THAT( 4.266766e-8, WithinRel( table( 1.136492e+2, 0. ) ) );
    CHECK_THAT( 3.48425e-26, WithinRel( table( 1.136492e+2, 1.976285e+2 ) ) );

    sab = inelastic->scatteringKernel( 700 );
    CHECK_THAT( 700     , WithinRel( sab.moderatorTemperature() ) );
    CHECK_THAT( 728.8872, WithinRel( sab.effectiveTemperature() ) );
    CHECK( true == sab.isEnergyTransferSymmetric() );
    table = sab.tabulatedScatteringKernel();
    CHECK_THAT( 0.         , WithinRel( table.lowerEnergyTransferLimit() ) );
    CHECK_THAT( 1.976285e+2, WithinRel( table.upperEnergyTransferLimit() ) );
    CHECK_THAT( 5.625091e-3, WithinRel( table.lowerMomentumTransferLimit() ) );
    CHECK_THAT( 1.136492e+2, WithinRel( table.upperMomentumTransferLimit() ) );
    CHECK_THAT( 2.731707e-3, WithinRel( table( 5.625091e-3, 0. ) ) );
    CHECK_THAT( min        , WithinRel( table( 5.625091e-3, 1.976285e+2 ) ) );
    CHECK_THAT( 3.117374e-7, WithinRel( table( 1.136492e+2, 0. ) ) );
    CHECK_THAT( 8.94715e-23, WithinRel( table( 1.136492e+2, 1.976285e+2 ) ) );

    sab = inelastic->scatteringKernel( 800 );
    CHECK_THAT( 800     , WithinRel( sab.moderatorTemperature() ) );
    CHECK_THAT( 825.3442, WithinRel( sab.effectiveTemperature() ) );
    CHECK( true == sab.isEnergyTransferSymmetric() );
    table = sab.tabulatedScatteringKernel();
    CHECK_THAT( 0.         , WithinRel( table.lowerEnergyTransferLimit() ) );
    CHECK_THAT( 1.976285e+2, WithinRel( table.upperEnergyTransferLimit() ) );
    CHECK_THAT( 5.625091e-3, WithinRel( table.lowerMomentumTransferLimit() ) );
    CHECK_THAT( 1.136492e+2, WithinRel( table.upperMomentumTransferLimit() ) );
    CHECK_THAT( 3.576777e-3, WithinRel( table( 5.625091e-3, 0. ) ) );
    CHECK_THAT( min        , WithinRel( table( 5.625091e-3, 1.976285e+2 ) ) );
    CHECK_THAT( 1.416596e-6, WithinRel( table( 1.136492e+2, 0. ) ) );
    CHECK_THAT( 3.37956e-20, WithinRel( table( 1.136492e+2, 1.976285e+2 ) ) );
  }

  void verifyLi7InLi7D( const ThermalScattering& tsl ) {

    verifyDocumentation( tsl.documentation() );

    CHECK( true == tsl.hasCoherentElasticScattering() );
    CHECK( true == tsl.hasIncoherentElasticScattering() );
    CHECK( true == tsl.hasElasticScattering() );
    CHECK( true == tsl.hasIncoherentInelasticScattering() );
    CHECK( true == tsl.hasInelasticScattering() );

    verifyCoherentElastic( tsl.coherentElasticScattering() );
    verifyIncoherentElastic( tsl.incoherentElasticScattering() );
  }

} // namespace bemetal
} // namespace tsl
