namespace tsl {

// test functions based on tsl-7Liin7LiD-mixed.endf
namespace li7inli7d {

  void verifyDocumentation( const Documentation& documentation ) {

    std::string description =
      " 7Li(7LiD) NNL        EVAL-MAR23 Zerkle, Holmes, Wormald          \n"
      " Ref. 1               DIST-AUG24 REV1-MAY24            20240830   \n"
      "---- ENDF/B-VIII.1    MATERIAL 3034         REVISION 1            \n"
      "----- THERMAL NEUTRON SCATTERING DATA                             \n"
      "------ ENDF-6                                                     \n"
      "                                                                  \n"
      "  Temperatures = 293.6 400 500 600 700 800 K                      \n"
      "                                                                  \n"
      " HISTORY                                                          \n"
      " -------                                                          \n"
      " This evaluation was generated by Naval Nuclear Laboratory (Mar   \n"
      " 2023) [1] using the FLASSH code [2].  The physical model is      \n"
      " based on the mixed elastic scattering treatment and includes     \n"
      " coherent elastic scattering, incoherent elastic scattering and   \n"
      " inelastic scattering contributions. This evaluation is intended  \n"
      " to be used with the companion D(7LiD) TSL evaluation when        \n"
      " modeling enriched 7LiD.                                          \n"
      "                                                                  \n"
      " THEORY                                                           \n"
      " ------                                                           \n"
      " Lithium hydride (LiD) has a fluorite (NaCl) type face-centered   \n"
      " cubic crystal structure with four Li and D atoms per unit call.  \n"
      " The inelastic scattering cross sections were calculated in the   \n"
      " incoherent approximation using the Li-7 partial phonon density   \n"
      " of states from a VASP/PHONON calculation of 7LiD based on the    \n"
      " crystal structure and lattice constant from [3].  The mixed      \n"
      " elastic scattering treatment was used to account for both        \n"
      " coherent and incoherent elastic scattering effects present in    \n"
      " this material.  The coherent elastic scattering component was    \n"
      " calculated in the cubic approxiation using the FLASSH            \n"
      " generalized coherent elastic scattering module using the 7LiD    \n"
      " crystal structure and measured room temperature lattice          \n"
      " constant of 4.0684 Ang [3] along with free atom coherent         \n"
      " scattering cross sections of 0.51 b for Li-7 from [5] and 2.483  \n"
      " b for D from [4]. The incoherent elastic scattering component    \n"
      " was calculated using the Debye-Waller factor derived from the    \n"
      " Li-7 partial phonon density of states and a Li-7 free atom       \n"
      " incoherent scattering cross section of 0.46 b from [5].  A Li-7  \n"
      " free atom total scattering cross section of 0.97 b was used to   \n"
      " ensure consistency with the ENDF/B-VIII.1 Li-7 evaluation. A     \n"
      " phonon order of 500 was used to ensure both the inelastic        \n"
      " scattering cross section and the S(alpha,beta) functions at      \n"
      " elevated temperatures were adaquately converged.                 \n"
      "                                                                  \n"
      " REFERENCES                                                       \n"
      " ----------                                                       \n"
      " 1. M. L. Zerkle, personal communications, Mar 9, 2023.           \n"
      "                                                                  \n"
      " 2. A. I. Hawari, et. al, FLASSH.beta3.2 User Guide (2022).       \n"
      "                                                                  \n"
      " 3. V. F. Sears, Neutron News, 3, 2-37 (1992).                    \n"
      "                                                                  \n"
      " 4. S. F. Mughabghab, Atlas of Neutron Resonances, 5th Edition,   \n"
      "    Elsevier, Amsterdam (2006).                                   \n"
      "                                                                  \n"
      " -----------------------------------------------------------------\n";

    CHECK( 0 == documentation.library() );
    CHECK( std::make_pair( 8, 1 ) == documentation.version() );
    CHECK( description == documentation.description() );
  }

  void verifyCoherentElastic( const std::optional< njoy::dryad::thermal::CoherentElasticScattering >& coherent ) {

    CHECK( std::nullopt != coherent );

    CHECK( 6 == coherent->numberModeratorTemperatures() );
    CHECK_THAT( 293.6, WithinRel( coherent->braggEdges()[0].temperature() ) );
    CHECK_THAT( 400. , WithinRel( coherent->braggEdges()[1].temperature() ) );
    CHECK_THAT( 700. , WithinRel( coherent->braggEdges()[4].temperature() ) );
    CHECK_THAT( 800. , WithinRel( coherent->braggEdges()[5].temperature() ) );
    CHECK( 112 == coherent->braggEdges()[0].numberBraggEdges() );
    CHECK( 112 == coherent->braggEdges()[1].numberBraggEdges() );
    CHECK( 112 == coherent->braggEdges()[4].numberBraggEdges() );
    CHECK( 112 == coherent->braggEdges()[5].numberBraggEdges() );
    CHECK( 112 == coherent->braggEdges()[0].energies().size() );
    CHECK( 112 == coherent->braggEdges()[1].energies().size() );
    CHECK( 112 == coherent->braggEdges()[4].energies().size() );
    CHECK( 112 == coherent->braggEdges()[5].energies().size() );
    CHECK( 112 == coherent->braggEdges()[0].values().size() );
    CHECK( 112 == coherent->braggEdges()[1].values().size() );
    CHECK( 112 == coherent->braggEdges()[4].values().size() );
    CHECK( 112 == coherent->braggEdges()[5].values().size() );

    CHECK_THAT( 3.706719e-3, WithinRel( coherent->braggEdges()[0].energies().front() ) );
    CHECK_THAT( 3.706719e-3, WithinRel( coherent->braggEdges()[1].energies().front() ) );
    CHECK_THAT( 3.706719e-3, WithinRel( coherent->braggEdges()[4].energies().front() ) );
    CHECK_THAT( 3.706719e-3, WithinRel( coherent->braggEdges()[5].energies().front() ) );
    CHECK_THAT( 5., WithinRel( coherent->braggEdges()[0].energies().back() ) );
    CHECK_THAT( 5., WithinRel( coherent->braggEdges()[1].energies().back() ) );
    CHECK_THAT( 5., WithinRel( coherent->braggEdges()[4].energies().back() ) );
    CHECK_THAT( 5., WithinRel( coherent->braggEdges()[5].energies().back() ) );

    CHECK_THAT( 3.757353e-3, WithinRel( coherent->braggEdges()[0].values().front() ) );
    CHECK_THAT( 3.686081e-3, WithinRel( coherent->braggEdges()[1].values().front() ) );
    CHECK_THAT( 3.428755e-3, WithinRel( coherent->braggEdges()[4].values().front() ) );
    CHECK_THAT( 3.337757e-3, WithinRel( coherent->braggEdges()[5].values().front() ) );
    CHECK_THAT( 8.406348e-2, WithinRel( coherent->braggEdges()[0].values().back() ) );
    CHECK_THAT( 6.996602e-2, WithinRel( coherent->braggEdges()[1].values().back() ) );
    CHECK_THAT( 4.402291e-2, WithinRel( coherent->braggEdges()[4].values().back() ) );
    CHECK_THAT( 3.861519e-2, WithinRel( coherent->braggEdges()[5].values().back() ) );
  }

  void verifyIncoherentElastic( const std::optional< njoy::dryad::thermal::IncoherentElasticScattering >& incoherent ) {

    CHECK( std::nullopt != incoherent );

    CHECK_THAT( 0.6017726, WithinRel( incoherent->boundCrossSection() ) );
    CHECK( 6 == incoherent->debyeWallerIntegral().temperatures().size() );
    CHECK( 6 == incoherent->debyeWallerIntegral().values().size() );
    CHECK_THAT( 293.6, WithinRel( incoherent->debyeWallerIntegral().temperatures()[0] ) );
    CHECK_THAT( 400. , WithinRel( incoherent->debyeWallerIntegral().temperatures()[1] ) );
    CHECK_THAT( 700. , WithinRel( incoherent->debyeWallerIntegral().temperatures()[4] ) );
    CHECK_THAT( 800. , WithinRel( incoherent->debyeWallerIntegral().temperatures()[5] ) );
    CHECK_THAT( 7.074031, WithinRel( incoherent->debyeWallerIntegral().values()[0] ) );
    CHECK_THAT( 9.081680, WithinRel( incoherent->debyeWallerIntegral().values()[1] ) );
    CHECK_THAT( 15.10002, WithinRel( incoherent->debyeWallerIntegral().values()[4] ) );
    CHECK_THAT( 17.15230, WithinRel( incoherent->debyeWallerIntegral().values()[5] ) );
  }

  void verifyLi7InLi7D( const ThermalScattering& tsl ) {

    verifyDocumentation( tsl.documentation() );

    CHECK( true == tsl.hasCoherentElasticScattering() );
    CHECK( true == tsl.hasIncoherentElasticScattering() );
    CHECK( true == tsl.hasElasticScattering() );
    CHECK( false == tsl.hasInelasticScattering() );

    verifyCoherentElastic( tsl.coherentElasticScattering() );
    verifyIncoherentElastic( tsl.incoherentElasticScattering() );
  }

} // namespace bemetal
} // namespace tsl
