"""
GNDS format related functions and components
"""
from __future__ import annotations
import typing
__all__: list[str] = ['StyleType']
class StyleType:
    """
    The style type of a GNDS file
    
    Members:
    
      Evaluation : The style type is evaluation
    """
    Evaluation: typing.ClassVar[StyleType]  # value = <StyleType.Evaluation: 1>
    __members__: typing.ClassVar[dict[str, StyleType]]  # value = {'Evaluation': <StyleType.Evaluation: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __ge__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __gt__(self, other: typing.Any) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __le__(self, other: typing.Any) -> bool:
        ...
    def __lt__(self, other: typing.Any) -> bool:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
