#include "njoy/format/ace/write/atomic/createSubshellTransitionDataBlock.hpp"
#include "njoy/format/ace/write/atomic/createElectronShellBlock.hpp"
#include "njoy/format/ace/write/atomic/createElectronSubshellBlock.hpp"

#include "njoy/format/ace/write/photoatomic/createPrincipalCrossSectionBlock.hpp"
#include "njoy/format/ace/write/photoatomic/createPhotoelectricCrossSectionBlock.hpp"
#include "njoy/format/ace/write/photoatomic/createIncoherentScatteringFunctionBlock.hpp"
#include "njoy/format/ace/write/photoatomic/createComptonProfileBlock.hpp"
#include "njoy/format/ace/write/photoatomic/createCoherentFormFactorBlock.hpp"
#include "njoy/format/ace/write/photoatomic/createFluorescenceDataBlock.hpp"
#include "njoy/format/ace/write/photoatomic/createHeatingNumbersBlock.hpp"

#include "njoy/format/ace/write/electroatomic/createPrincipalCrossSectionBlock.hpp"
#include "njoy/format/ace/write/electroatomic/createElasticCrossSectionBlock.hpp"
#include "njoy/format/ace/write/electroatomic/createElasticAngularDistributionBlock.hpp"
#include "njoy/format/ace/write/electroatomic/createBremsstrahlungDistributionBlock.hpp"
#include "njoy/format/ace/write/electroatomic/createIonisationDistributionBlocks.hpp"
#include "njoy/format/ace/write/electroatomic/createExcitationBlock.hpp"
#include "njoy/format/ace/write/electroatomic/createBremsstrahlungBlock.hpp"
