// include Catch2
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
using Catch::Matchers::WithinRel;

// what we are testing
#include "njoy/format/gnds/write/pops/insertParticleDatabase.hpp"

// other includes
#include <sstream>
#include "pugixml.hpp"
#include "njoy/format/gnds/write/Options.hpp"

// convenience typedefs
using namespace njoy::dryad;
using namespace njoy::format;

std::string chunkAtomic();
std::string chunkNuclear();
std::string chunkElementMass();

SCENARIO( "insertParticleDatabase" ) {

  GIVEN( "a parent node and a particle database" ) {

    gnds::write::Options options;

    THEN( "a particle database can be inserted for typical atomic interactions" ) {

      std::vector< id::ParticleID > identifiers = {

        id::ParticleID::photon(), id::ParticleID::positron(), id::ParticleID::electron(),
        id::ParticleID( "H" )
      };
      ParticleDatabase particles( identifiers );

      // no element mass

      pugi::xml_document parent;
      auto node = gnds::write::pops::insertParticleDatabase( parent, options, particles, "eval" );

      std::ostringstream out;
      node.print( out, "  " );
      CHECK( out.str() == chunkAtomic() );

      // with element mass

      particles.particle( id::ParticleID( "H" ) ).mass( 1. );

      parent.reset();
      node = gnds::write::pops::insertParticleDatabase( parent, options, particles, "eval" );

      out.str( "" );
      node.print( out, "  " );
      CHECK( out.str() == chunkAtomicWithMass() );
    } // THEN

    THEN( "a particle database can be inserted for typical nuclear interactions" ) {

      std::vector< id::ParticleID > identifiers = {

        id::ParticleID::photon(),
        id::ParticleID::neutron(),
        id::ParticleID::proton(), id::ParticleID::deuteron(), id::ParticleID::triton(),
        id::ParticleID::helion(), id::ParticleID::alpha(),
        id::ParticleID( "H2[all]" ),  id::ParticleID( "Li6[all]" ),
        id::ParticleID( "Li7" ), id::ParticleID( "Li7_e1" ), id::ParticleID( "Li7_e2" ),
        id::ParticleID( "Li7[all]" ), id::ParticleID( "Li8[all]" )
      };
      ParticleDatabase particles( identifiers );

      pugi::xml_document parent;
      auto node = gnds::write::pops::insertParticleDatabase( parent, options, particles, "eval" );

      std::ostringstream out;
      node.print( out, "  " );
      CHECK( out.str() == chunkNuclear() );
    } // THEN
  } // GIVEN
} // SCENARIO

std::string chunkAtomic() {

  return "<PoPs name=\"particles\" version=\"1.0\" format=\"2.1\">\n"
         "  <gaugeBosons>\n"
         "    <gaugeBoson id=\"g\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"0\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </gaugeBoson>\n"
         "  </gaugeBosons>\n"
         "  <leptons>\n"
         "    <lepton id=\"e-\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"0.0005485799090441\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"-1\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </lepton>\n"
         "    <lepton id=\"e+\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"0.0005485799090441\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"-1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"1\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </lepton>\n"
         "  </leptons>\n"
         "  <chemicalElements>\n"
         "    <chemicalElement symbol=\"H\" Z=\"1\" name=\"Hydrogen\" />\n"
         "  </chemicalElements>\n"
         "</PoPs>\n";
}

std::string chunkAtomicWithMass() {

  return "<PoPs name=\"particles\" version=\"1.0\" format=\"2.1\">\n"
         "  <gaugeBosons>\n"
         "    <gaugeBoson id=\"g\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"0\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </gaugeBoson>\n"
         "  </gaugeBosons>\n"
         "  <leptons>\n"
         "    <lepton id=\"e-\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"0.0005485799090441\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"-1\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </lepton>\n"
         "    <lepton id=\"e+\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"0.0005485799090441\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"-1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"1\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </lepton>\n"
         "  </leptons>\n"
         "  <chemicalElements>\n"
         "    <chemicalElement symbol=\"H\" Z=\"1\" name=\"Hydrogen\">\n"
         "      <isotopes>\n"
         "        <isotope symbol=\"H0\" A=\"0\">\n"
         "          <nuclides>\n"
         "            <nuclide id=\"H0\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"1\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"h0\" index=\"0\">\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"1\" unit=\"e\" />\n"
         "                </charge>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "          </nuclides>\n"
         "        </isotope>\n"
         "      </isotopes>\n"
         "    <chemicalElement/>\n"
         "  </chemicalElements>\n"
         "</PoPs>\n";
}

std::string chunkNuclear() {

  return "<PoPs name=\"particles\" version=\"1.0\" format=\"2.1\">\n"
         "  <aliases>\n"
         "    <alias id=\"d\" pid=\"h2\" />\n"
         "    <alias id=\"t\" pid=\"h3\" />\n"
         "    <alias id=\"h\" pid=\"he3\" />\n"
         "    <alias id=\"a\" pid=\"he4\" />\n"
         "  </aliases>\n"
         "  <gaugeBosons>\n"
         "    <gaugeBoson id=\"g\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"0\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </gaugeBoson>\n"
         "  </gaugeBosons>\n"
         "  <baryons>\n"
         "    <baryon id=\"n\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"1.00866491606\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </baryon>\n"
         "    <baryon id=\"p\">\n"
         "      <mass>\n"
         "        <double label=\"eval\" value=\"1.007276466579\" unit=\"amu\" />\n"
         "      </mass>\n"
         "      <spin>\n"
         "        <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "      </spin>\n"
         "      <parity>\n"
         "        <integer label=\"eval\" value=\"1\" />\n"
         "      </parity>\n"
         "      <charge>\n"
         "        <integer label=\"eval\" value=\"1\" unit=\"e\" />\n"
         "      </charge>\n"
         "    </baryon>\n"
         "  </baryons>\n"
         "  <chemicalElements>\n"
         "    <chemicalElement symbol=\"H\" Z=\"1\" name=\"Hydrogen\">\n"
         "      <isotopes>\n"
         "        <isotope symbol=\"H2\" A=\"2\">\n"
         "          <nuclides>\n"
         "            <nuclide id=\"H2\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"2.014101777844\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"h2\" index=\"0\">\n"
         "                <spin>\n"
         "                  <fraction label=\"eval\" value=\"1\" unit=\"hbar\" />\n"
         "                </spin>\n"
         "                <parity>\n"
         "                  <integer label=\"eval\" value=\"1\" />\n"
         "                </parity>\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"1\" unit=\"e\" />\n"
         "                </charge>\n"
         "                <energy>\n"
         "                  <double label=\"eval\" value=\"0\" unit=\"eV\" />\n"
         "                </energy>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "            <nuclide id=\"H2[all]\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"2.014101777844\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"h2[all]\" index=\"999\">\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"1\" unit=\"e\" />\n"
         "                </charge>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "          </nuclides>\n"
         "        </isotope>\n"
         "        <isotope symbol=\"H3\" A=\"3\">\n"
         "          <nuclides>\n"
         "            <nuclide id=\"H3\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"3.01604928132\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"h3\" index=\"0\">\n"
         "                <spin>\n"
         "                  <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "                </spin>\n"
         "                <parity>\n"
         "                  <integer label=\"eval\" value=\"1\" />\n"
         "                </parity>\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"1\" unit=\"e\" />\n"
         "                </charge>\n"
         "                <energy>\n"
         "                  <double label=\"eval\" value=\"0\" unit=\"eV\" />\n"
         "                </energy>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "          </nuclides>\n"
         "        </isotope>\n"
         "      </isotopes>\n"
         "    </chemicalElement>\n"
         "    <chemicalElement symbol=\"He\" Z=\"2\" name=\"Helium\">\n"
         "      <isotopes>\n"
         "        <isotope symbol=\"He3\" A=\"3\">\n"
         "          <nuclides>\n"
         "            <nuclide id=\"He3\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"3.01602932197\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"he3\" index=\"0\">\n"
         "                <spin>\n"
         "                  <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "                </spin>\n"
         "                <parity>\n"
         "                  <integer label=\"eval\" value=\"1\" />\n"
         "                </parity>\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"2\" unit=\"e\" />\n"
         "                </charge>\n"
         "                <energy>\n"
         "                  <double label=\"eval\" value=\"0\" unit=\"eV\" />\n"
         "                </energy>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "          </nuclides>\n"
         "        </isotope>\n"
         "        <isotope symbol=\"He4\" A=\"4\">\n"
         "          <nuclides>\n"
         "            <nuclide id=\"He4\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"4.00260325413\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"he4\" index=\"0\">\n"
         "                <spin>\n"
         "                  <fraction label=\"eval\" value=\"0\" unit=\"hbar\" />\n"
         "                </spin>\n"
         "                <parity>\n"
         "                  <integer label=\"eval\" value=\"1\" />\n"
         "                </parity>\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"2\" unit=\"e\" />\n"
         "                </charge>\n"
         "                <energy>\n"
         "                  <double label=\"eval\" value=\"0\" unit=\"eV\" />\n"
         "                </energy>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "          </nuclides>\n"
         "        </isotope>\n"
         "      </isotopes>\n"
         "    </chemicalElement>\n"
         "    <chemicalElement symbol=\"Li\" Z=\"3\" name=\"Lithium\">\n"
         "      <isotopes>\n"
         "        <isotope symbol=\"Li6\" A=\"6\">\n"
         "          <nuclides>\n"
         "            <nuclide id=\"Li6[all]\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"6.01512288742\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"li6[all]\" index=\"999\">\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"3\" unit=\"e\" />\n"
         "                </charge>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "          </nuclides>\n"
         "        </isotope>\n"
         "        <isotope symbol=\"Li7\" A=\"7\">\n"
         "          <nuclides>\n"
         "            <nuclide id=\"Li7\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"7.01600343426\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"li7\" index=\"0\">\n"
         "                <spin>\n"
         "                  <fraction label=\"eval\" value=\"3/2\" unit=\"hbar\" />\n"
         "                </spin>\n"
         "                <parity>\n"
         "                  <integer label=\"eval\" value=\"-1\" />\n"
         "                </parity>\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"3\" unit=\"e\" />\n"
         "                </charge>\n"
         "                <energy>\n"
         "                  <double label=\"eval\" value=\"0\" unit=\"eV\" />\n"
         "                </energy>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "            <nuclide id=\"Li7_e1\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"7.01600343426\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"li7_e1\" index=\"1\">\n"
         "                <spin>\n"
         "                  <fraction label=\"eval\" value=\"1/2\" unit=\"hbar\" />\n"
         "                </spin>\n"
         "                <parity>\n"
         "                  <integer label=\"eval\" value=\"-1\" />\n"
         "                </parity>\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"3\" unit=\"e\" />\n"
         "                </charge>\n"
         "                <energy>\n"
         "                  <double label=\"eval\" value=\"477612\" unit=\"eV\" />\n"
         "                </energy>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "            <nuclide id=\"Li7_e2\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"7.01600343426\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"li7_e2\" index=\"2\">\n"
         "                <spin>\n"
         "                  <fraction label=\"eval\" value=\"7/2\" unit=\"hbar\" />\n"
         "                </spin>\n"
         "                <parity>\n"
         "                  <integer label=\"eval\" value=\"-1\" />\n"
         "                </parity>\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"3\" unit=\"e\" />\n"
         "                </charge>\n"
         "                <energy>\n"
         "                  <double label=\"eval\" value=\"4630000\" unit=\"eV\" />\n"
         "                </energy>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "            <nuclide id=\"Li7[all]\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"7.01600343426\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"li7[all]\" index=\"999\">\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"3\" unit=\"e\" />\n"
         "                </charge>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "          </nuclides>\n"
         "        </isotope>\n"
         "        <isotope symbol=\"Li8\" A=\"8\">\n"
         "          <nuclides>\n"
         "            <nuclide id=\"Li8[all]\">\n"
         "              <mass>\n"
         "                <double label=\"eval\" value=\"8.022486244\" unit=\"amu\" />\n"
         "              </mass>\n"
         "              <charge>\n"
         "                <integer label=\"eval\" value=\"0\" unit=\"e\" />\n"
         "              </charge>\n"
         "              <nucleus id=\"li8[all]\" index=\"999\">\n"
         "                <charge>\n"
         "                  <integer label=\"eval\" value=\"3\" unit=\"e\" />\n"
         "                </charge>\n"
         "              </nucleus>\n"
         "            </nuclide>\n"
         "          </nuclides>\n"
         "        </isotope>\n"
         "      </isotopes>\n"
         "    </chemicalElement>\n"
         "  </chemicalElements>\n"
         "</PoPs>\n";
}
