#######################################################################
# Setup
#######################################################################

enable_testing()

FetchContent_MakeAvailable( Catch2 )

function( add_cpp_test name source )

  set( test_name "njoy.${name}.test" )
  add_executable( ${test_name} ${source} )
  add_test( NAME ${test_name} COMMAND ${test_name} )
  target_link_libraries( ${test_name} PRIVATE njoy )
  target_link_libraries( ${test_name} PRIVATE Catch2::Catch2WithMain )

  file( GLOB resources "resources/*" )
  foreach( resource ${resources} )
    file( COPY "${resource}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}" )
  endforeach()

endfunction()

#######################################################################
# Unit testing directories
#######################################################################

message( STATUS "Adding njoy C++ unit testing" )

# njoy tests

add_cpp_test( configuration                                                             configuration.test.cpp )
add_cpp_test( matrix                                                                    matrix.test.cpp )

# dryad tests

add_cpp_test( dryad.base.UniformDistribution                                            dryad/base/UniformDistribution.test.cpp )

add_cpp_test( dryad.atomic.ElectronSubshellConfiguration                                dryad/atomic/ElectronSubshellConfiguration.test.cpp )
add_cpp_test( dryad.atomic.NonRadiativeTransitionData                                   dryad/atomic/NonRadiativeTransitionData.test.cpp )
add_cpp_test( dryad.atomic.RadiativeTransitionData                                      dryad/atomic/RadiativeTransitionData.test.cpp )

add_cpp_test( dryad.covariance.base.Metadata                                            dryad/covariance/base/Metadata.test.cpp )
add_cpp_test( dryad.covariance.base.CovarianceMatrix                                    dryad/covariance/base/CovarianceMatrix.test.cpp )
add_cpp_test( dryad.covariance.VarianceScaling                                          dryad/covariance/VarianceScaling.test.cpp )
add_cpp_test( dryad.covariance.CrossSectionMetadata                                     dryad/covariance/CrossSectionMetadata.test.cpp )
add_cpp_test( dryad.covariance.CrossSectionCovarianceMatrix                             dryad/covariance/CrossSectionCovarianceMatrix.test.cpp )
add_cpp_test( dryad.covariance.AngularDistributionMetadata                              dryad/covariance/AngularDistributionMetadata.test.cpp )
add_cpp_test( dryad.covariance.AngularDistributionCovarianceMatrix                      dryad/covariance/AngularDistributionCovarianceMatrix.test.cpp )
add_cpp_test( dryad.covariance.AngularDistributionCovarianceData                        dryad/covariance/AngularDistributionCovarianceData.test.cpp )
add_cpp_test( dryad.covariance.ProductMultiplicityMetadata                              dryad/covariance/ProductMultiplicityMetadata.test.cpp )
add_cpp_test( dryad.covariance.ProductMultiplicityCovarianceMatrix                      dryad/covariance/ProductMultiplicityCovarianceMatrix.test.cpp )
add_cpp_test( dryad.covariance.LinearCombinationCovariance                              dryad/covariance/LinearCombinationCovariance.test.cpp )
add_cpp_test( dryad.covariance.CrossSectionCovarianceData                               dryad/covariance/CrossSectionCovarianceData.test.cpp )
add_cpp_test( dryad.covariance.CovarianceData                                           dryad/covariance/CovarianceData.test.cpp )

add_cpp_test( dryad.id.EnergyGroup                                                      dryad/id/EnergyGroup.test.cpp )
add_cpp_test( dryad.id.ElectronSubshellID                                               dryad/id/ElectronSubshellID.test.cpp )
add_cpp_test( dryad.id.ElementID                                                        dryad/id/ElementID.test.cpp )
add_cpp_test( dryad.id.LevelID                                                          dryad/id/LevelID.test.cpp )
add_cpp_test( dryad.id.ParticleID                                                       dryad/id/ParticleID.test.cpp )
add_cpp_test( dryad.id.ReactionType                                                     dryad/id/ReactionType.test.cpp )
add_cpp_test( dryad.id.ReactionID                                                       dryad/id/ReactionID.test.cpp )
add_cpp_test( dryad.id.ChannelID                                                        dryad/id/ChannelID.test.cpp )

add_cpp_test( dryad.resonances.ParticlePair                                             dryad/resonances/ParticlePair.test.cpp )
add_cpp_test( dryad.resonances.TabulatedRadius                                          dryad/resonances/TabulatedRadius.test.cpp )
add_cpp_test( dryad.resonances.ChannelRadii                                             dryad/resonances/ChannelRadii.test.cpp )
add_cpp_test( dryad.resonances.ChannelQuantumNumbers                                    dryad/resonances/ChannelQuantumNumbers.test.cpp )
add_cpp_test( dryad.resonances.HardSpherePenetrability                                  dryad/resonances/HardSpherePenetrability.test.cpp )
add_cpp_test( dryad.resonances.HardSphereShiftFactor                                    dryad/resonances/HardSphereShiftFactor.test.cpp )
add_cpp_test( dryad.resonances.HardSpherePhaseShift                                     dryad/resonances/HardSpherePhaseShift.test.cpp )
add_cpp_test( dryad.resonances.CoulombPenetrability                                     dryad/resonances/CoulombPenetrability.test.cpp )
add_cpp_test( dryad.resonances.CoulombShiftFactor                                       dryad/resonances/CoulombShiftFactor.test.cpp )
add_cpp_test( dryad.resonances.CoulombPhaseShift                                        dryad/resonances/CoulombPhaseShift.test.cpp )
add_cpp_test( dryad.resonances.CoulombPhaseShiftDifference                              dryad/resonances/CoulombPhaseShiftDifference.test.cpp )
add_cpp_test( dryad.resonances.TabulatedWaveFunction                                    dryad/resonances/TabulatedWaveFunction.test.cpp )
add_cpp_test( dryad.resonances.FrohnerBackground                                        dryad/resonances/FrohnerBackground.test.cpp )
add_cpp_test( dryad.resonances.SammyBackground                                          dryad/resonances/SammyBackground.test.cpp )
add_cpp_test( dryad.resonances.TabulatedBackground                                      dryad/resonances/TabulatedBackground.test.cpp )
add_cpp_test( dryad.resonances.Channel                                                  dryad/resonances/Channel.test.cpp )
add_cpp_test( dryad.resonances.ResonanceTable                                           dryad/resonances/ResonanceTable.test.cpp )
add_cpp_test( dryad.resonances.calculator.Constant                                      dryad/resonances/calculator/Constant.test.cpp )
add_cpp_test( dryad.resonances.calculator.ShiftFactor                                   dryad/resonances/calculator/ShiftFactor.test.cpp )
add_cpp_test( dryad.resonances.calculator.ReichMoore                                    dryad/resonances/calculator/ReichMoore.test.cpp )
add_cpp_test( dryad.resonances.SpinGroup                                                dryad/resonances/SpinGroup.test.cpp )
add_cpp_test( dryad.resonances.CompoundSystem                                           dryad/resonances/CompoundSystem.test.cpp )
add_cpp_test( dryad.resonances.TabulatedLevelSpacing                                    dryad/resonances/TabulatedLevelSpacing.test.cpp )
add_cpp_test( dryad.resonances.TabulatedAverageWidths                                    dryad/resonances/TabulatedAverageWidths.test.cpp )

add_cpp_test( dryad.thermal.TabulatedScatteringKernelFunction                           dryad/thermal/TabulatedScatteringKernelFunction.test.cpp )
add_cpp_test( dryad.thermal.TabulatedScatteringKernel                                   dryad/thermal/TabulatedScatteringKernel.test.cpp )
add_cpp_test( dryad.thermal.BraggEdgeData                                               dryad/thermal/BraggEdgeData.test.cpp )
add_cpp_test( dryad.thermal.DebyeWallerIntegralData                                     dryad/thermal/DebyeWallerIntegralData.test.cpp )
add_cpp_test( dryad.thermal.CoherentElasticScattering                                   dryad/thermal/CoherentElasticScattering.test.cpp )
add_cpp_test( dryad.thermal.IncoherentElasticScattering                                 dryad/thermal/IncoherentElasticScattering.test.cpp )

add_cpp_test( dryad.Documentation                                                       dryad/Documentation.test.cpp )

add_cpp_test( dryad.Particle                                                            dryad/Particle.test.cpp )
add_cpp_test( dryad.ParticleDatabase                                                    dryad/ParticleDatabase.test.cpp )

add_cpp_test( dryad.CoherentDistributionData                                            dryad/CoherentDistributionData.test.cpp )
add_cpp_test( dryad.IncoherentDistributionData                                          dryad/IncoherentDistributionData.test.cpp )

add_cpp_test( dryad.TabulatedFormFactor                                                 dryad/TabulatedFormFactor.test.cpp )
add_cpp_test( dryad.TabulatedScatteringFunction                                         dryad/TabulatedScatteringFunction.test.cpp )
add_cpp_test( dryad.PolynomialMultiplicity                                              dryad/PolynomialMultiplicity.test.cpp )
add_cpp_test( dryad.TabulatedMultiplicity                                               dryad/TabulatedMultiplicity.test.cpp )
add_cpp_test( dryad.TabulatedAverageCosine                                              dryad/TabulatedAverageCosine.test.cpp )
add_cpp_test( dryad.TabulatedAverageEnergy                                              dryad/TabulatedAverageEnergy.test.cpp )
add_cpp_test( dryad.LegendreAngularDistributionFunction                                 dryad/LegendreAngularDistributionFunction.test.cpp )
add_cpp_test( dryad.LegendreAngularDistribution                                         dryad/LegendreAngularDistribution.test.cpp )
add_cpp_test( dryad.LegendreAngularDistributions                                        dryad/LegendreAngularDistributions.test.cpp )
add_cpp_test( dryad.TabulatedAngularDistributionFunction                                dryad/TabulatedAngularDistributionFunction.test.cpp )
add_cpp_test( dryad.TabulatedAngularDistribution                                        dryad/TabulatedAngularDistribution.test.cpp )
add_cpp_test( dryad.TabulatedAngularDistributions                                       dryad/TabulatedAngularDistributions.test.cpp )
add_cpp_test( dryad.TabulatedComptonProfile                                             dryad/TabulatedComptonProfile.test.cpp )
add_cpp_test( dryad.TabulatedComptonProfileFunction                                     dryad/TabulatedComptonProfileFunction.test.cpp )
add_cpp_test( dryad.UniformAngularDistribution                                          dryad/UniformAngularDistribution.test.cpp )
add_cpp_test( dryad.UniformAngularDistributions                                         dryad/UniformAngularDistributions.test.cpp )
add_cpp_test( dryad.UniformEnergyDistribution                                           dryad/UniformEnergyDistribution.test.cpp )
add_cpp_test( dryad.UniformEnergyDistributions                                          dryad/UniformEnergyDistributions.test.cpp )
add_cpp_test( dryad.TabulatedEnergyDistributionFunction                                 dryad/TabulatedEnergyDistributionFunction.test.cpp )
add_cpp_test( dryad.TabulatedEnergyDistribution                                         dryad/TabulatedEnergyDistribution.test.cpp )
add_cpp_test( dryad.TabulatedEnergyDistributions                                        dryad/TabulatedEnergyDistributions.test.cpp )
add_cpp_test( dryad.TwoBodyDistributionData                                             dryad/TwoBodyDistributionData.test.cpp )
add_cpp_test( dryad.UncorrelatedDistributionData                                        dryad/UncorrelatedDistributionData.test.cpp )
add_cpp_test( dryad.ReactionProduct                                                     dryad/ReactionProduct.test.cpp )
add_cpp_test( dryad.TabulatedCrossSection                                               dryad/TabulatedCrossSection.test.cpp )
add_cpp_test( dryad.Reaction                                                            dryad/Reaction.test.cpp )

add_cpp_test( dryad.ProjectileTarget                                                    dryad/ProjectileTarget.test.cpp )
add_cpp_test( dryad.AtomicRelaxation                                                    dryad/AtomicRelaxation.test.cpp )
add_cpp_test( dryad.ThermalScattering                                                   dryad/ThermalScattering.test.cpp )

add_cpp_test( dryad.format.createIndex                                                  dryad/format/createIndex.test.cpp )
add_cpp_test( dryad.format.createVector                                                 dryad/format/createVector.test.cpp )
add_cpp_test( dryad.format.adjustScatterLevel                                           dryad/format/adjustScatterLevel.test.cpp )
add_cpp_test( dryad.format.collectParticleIdentifiers                                   dryad/format/collectParticleIdentifiers.test.cpp )

add_cpp_test( dryad.format.ace.createProjectileIdentifier                               dryad/format/ace/createProjectileIdentifier.test.cpp )
add_cpp_test( dryad.format.ace.createTabulatedScatteringFunction                        dryad/format/ace/createTabulatedScatteringFunction.test.cpp )
add_cpp_test( dryad.format.ace.createTabulatedAngularDistributionFunction               dryad/format/ace/createTabulatedAngularDistributionFunction.test.cpp )
add_cpp_test( dryad.format.ace.createTabulatedEnergyDistributionFunction                dryad/format/ace/createTabulatedEnergyDistributionFunction.test.cpp )
add_cpp_test( dryad.format.ace.continuous.createTabulatedCrossSection                   dryad/format/ace/continuous/createTabulatedCrossSection.test.cpp )
add_cpp_test( dryad.format.ace.continuous.createElasticTabulatedCrossSection            dryad/format/ace/continuous/createElasticTabulatedCrossSection.test.cpp )
add_cpp_test( dryad.format.ace.continuous.createTotalTabulatedCrossSection              dryad/format/ace/continuous/createTotalTabulatedCrossSection.test.cpp )
add_cpp_test( dryad.format.ace.continuous.createReaction                                dryad/format/ace/continuous/createReaction.test.cpp )
add_cpp_test( dryad.format.ace.continuous.createReactions                               dryad/format/ace/continuous/createReactions.test.cpp )
add_cpp_test( dryad.format.ace.continuous.createProjectileTarget                        dryad/format/ace/continuous/createProjectileTarget.test.cpp )
add_cpp_test( dryad.format.ace.photonuclear.createReaction                              dryad/format/ace/photonuclear/createReaction.test.cpp )
add_cpp_test( dryad.format.ace.photonuclear.createReactions                             dryad/format/ace/photonuclear/createReactions.test.cpp )
add_cpp_test( dryad.format.ace.photonuclear.createProjectileTarget                      dryad/format/ace/photonuclear/createProjectileTarget.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createPdfFromCdf                           dryad/format/ace/electroatomic/createPdfFromCdf.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createReactionIdentifiers                  dryad/format/ace/electroatomic/createReactionIdentifiers.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createPartialReactionIdentifiers           dryad/format/ace/electroatomic/createPartialReactionIdentifiers.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createTabulatedCrossSections               dryad/format/ace/electroatomic/createTabulatedCrossSections.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createReactions                            dryad/format/ace/electroatomic/createReactions.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createProjectileTarget                     dryad/format/ace/electroatomic/createProjectileTarget.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createReactionIdentifiers                    dryad/format/ace/photoatomic/createReactionIdentifiers.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createTabulatedComptonProfile                dryad/format/ace/photoatomic/createTabulatedComptonProfile.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createTabulatedComptonProfiles               dryad/format/ace/photoatomic/createTabulatedComptonProfiles.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createPartialReactionIdentifiers             dryad/format/ace/photoatomic/createPartialReactionIdentifiers.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createTabulatedCrossSections                 dryad/format/ace/photoatomic/createTabulatedCrossSections.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createReactionProducts                       dryad/format/ace/photoatomic/createReactionProducts.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createReactions                              dryad/format/ace/photoatomic/createReactions.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createProjectileTarget                       dryad/format/ace/photoatomic/createProjectileTarget.test.cpp )
add_cpp_test( dryad.format.ace.createProjectileTargetFromFile                           dryad/format/ace/createProjectileTargetFromFile.test.cpp )

add_cpp_test( dryad.format.ace.atomic.createAceSubshellTransitionDataBlock              dryad/format/ace/atomic/createAceSubshellTransitionDataBlock.test.cpp )
add_cpp_test( dryad.format.ace.atomic.createAceElectronShellBlock                       dryad/format/ace/atomic/createAceElectronShellBlock.test.cpp )
add_cpp_test( dryad.format.ace.atomic.createAceElectronSubshellBlock                    dryad/format/ace/atomic/createAceElectronSubshellBlock.test.cpp )

add_cpp_test( dryad.format.ace.electroatomic.createAcePrincipalCrossSectionBlock        dryad/format/ace/electroatomic/createAcePrincipalCrossSectionBlock.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createAceElasticCrossSectionBlock          dryad/format/ace/electroatomic/createAceElasticCrossSectionBlock.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createAceElasticAngularDistributionBlock   dryad/format/ace/electroatomic/createAceElasticAngularDistributionBlock.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createAceBremsstrahlungDistributionBlock   dryad/format/ace/electroatomic/createAceBremsstrahlungDistributionBlock.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createAceIonisationDistributionBlocks      dryad/format/ace/electroatomic/createAceIonisationDistributionBlocks.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createAceExcitationBlock                   dryad/format/ace/electroatomic/createAceExcitationBlock.test.cpp )
add_cpp_test( dryad.format.ace.electroatomic.createAceBremsstrahlungBlock               dryad/format/ace/electroatomic/createAceBremsstrahlungBlock.test.cpp )

add_cpp_test( dryad.format.ace.photoatomic.createAcePrincipalCrossSectionBlock          dryad/format/ace/photoatomic/createAcePrincipalCrossSectionBlock.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createAcePhotoelectricCrossSectionBlock      dryad/format/ace/photoatomic/createAcePhotoelectricCrossSectionBlock.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createAceHeatingNumbersBlock                 dryad/format/ace/photoatomic/createAceHeatingNumbersBlock.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createAceFluorescenceDataBlock               dryad/format/ace/photoatomic/createAceFluorescenceDataBlock.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createAceIncoherentScatteringFunctionBlock   dryad/format/ace/photoatomic/createAceIncoherentScatteringFunctionBlock.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createAceComptonProfileBlock                 dryad/format/ace/photoatomic/createAceComptonProfileBlock.test.cpp )
add_cpp_test( dryad.format.ace.photoatomic.createAceCoherentFormFactorBlock             dryad/format/ace/photoatomic/createAceCoherentFormFactorBlock.test.cpp )

add_cpp_test( dryad.format.endf.ReactionInformation                                     dryad/format/endf/ReactionInformation.test.cpp )
add_cpp_test( dryad.format.endf.createBoundaries                                        dryad/format/endf/createBoundaries.test.cpp )
add_cpp_test( dryad.format.endf.createReferenceFrame                                    dryad/format/endf/createReferenceFrame.test.cpp )
add_cpp_test( dryad.format.endf.createInterpolant                                       dryad/format/endf/createInterpolant.test.cpp )
add_cpp_test( dryad.format.endf.createInterpolants                                      dryad/format/endf/createInterpolants.test.cpp )
add_cpp_test( dryad.format.endf.createProjectileIdentifier                              dryad/format/endf/createProjectileIdentifier.test.cpp )
add_cpp_test( dryad.format.endf.createProductIdentifier                                 dryad/format/endf/createProductIdentifier.test.cpp )
add_cpp_test( dryad.format.endf.createTargetIdentifier                                  dryad/format/endf/createTargetIdentifier.test.cpp )
add_cpp_test( dryad.format.endf.createInteractionType                                   dryad/format/endf/createInteractionType.test.cpp )
add_cpp_test( dryad.format.endf.createComplexBreakUpParticles                           dryad/format/endf/createComplexBreakUpParticles.test.cpp )
add_cpp_test( dryad.format.endf.resonances.createTabulatedRadius                        dryad/format/endf/resonances/createTabulatedRadius.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf3.createSpinGroups                        dryad/format/endf/resonances/lrf3/createSpinGroups.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf3.createCompoundSystem                    dryad/format/endf/resonances/lrf3/createCompoundSystem.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createBoundaryCondition                 dryad/format/endf/resonances/lrf7/createBoundaryCondition.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createFormalism                         dryad/format/endf/resonances/lrf7/createFormalism.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createKinematics                        dryad/format/endf/resonances/lrf7/createKinematics.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createReactionIdentifiers               dryad/format/endf/resonances/lrf7/createReactionIdentifiers.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createParticlePairs                     dryad/format/endf/resonances/lrf7/createParticlePairs.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createFrohnerBackground                 dryad/format/endf/resonances/lrf7/createFrohnerBackground.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createSammyBackground                   dryad/format/endf/resonances/lrf7/createSammyBackground.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createTabulatedBackground               dryad/format/endf/resonances/lrf7/createTabulatedBackground.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createChannels                          dryad/format/endf/resonances/lrf7/createChannels.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createSpinGroups                        dryad/format/endf/resonances/lrf7/createSpinGroups.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createCompoundSystem                    dryad/format/endf/resonances/lrf7/createCompoundSystem.test.cpp )
add_cpp_test( dryad.format.endf.thermal.createBraggEdges                                dryad/format/endf/thermal/createBraggEdges.test.cpp )
add_cpp_test( dryad.format.endf.thermal.createDebyeWallerIntegralData                   dryad/format/endf/thermal/createDebyeWallerIntegralData.test.cpp )
add_cpp_test( dryad.format.endf.thermal.createCoherentElasticScattering                 dryad/format/endf/thermal/createCoherentElasticScattering.test.cpp )
add_cpp_test( dryad.format.endf.thermal.createIncoherentElasticScattering               dryad/format/endf/thermal/createIncoherentElasticScattering.test.cpp )
add_cpp_test( dryad.format.endf.atomic.createElectronSubshellID                         dryad/format/endf/atomic/createElectronSubshellID.test.cpp )
add_cpp_test( dryad.format.endf.atomic.createElectronSubshellConfiguration              dryad/format/endf/atomic/createElectronSubshellConfiguration.test.cpp )
add_cpp_test( dryad.format.endf.covariance.createMatrix                                 dryad/format/endf/covariance/createMatrix.test.cpp )
add_cpp_test( dryad.format.endf.covariance.createVarianceScaling                        dryad/format/endf/covariance/createVarianceScaling.test.cpp )
add_cpp_test( dryad.format.endf.covariance.createCrossSectionCovarianceMatrix           dryad/format/endf/covariance/createCrossSectionCovarianceMatrix.test.cpp )
add_cpp_test( dryad.format.endf.covariance.createCrossSectionCovarianceData             dryad/format/endf/covariance/createCrossSectionCovarianceData.test.cpp )
add_cpp_test( dryad.format.endf.covariance.createAngularDistributionCovarianceMatrix    dryad/format/endf/covariance/createAngularDistributionCovarianceMatrix.test.cpp )
add_cpp_test( dryad.format.endf.covariance.createAngularDistributionCovarianceData      dryad/format/endf/covariance/createAngularDistributionCovarianceData.test.cpp )
add_cpp_test( dryad.format.endf.covariance.createCovarianceData                         dryad/format/endf/covariance/createCovarianceData.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedCrossSection                             dryad/format/endf/createTabulatedCrossSection.test.cpp )
add_cpp_test( dryad.format.endf.createPolynomialMultiplicity                            dryad/format/endf/createPolynomialMultiplicity.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedMultiplicity                             dryad/format/endf/createTabulatedMultiplicity.test.cpp )
add_cpp_test( dryad.format.endf.createMultiplicity                                      dryad/format/endf/createMultiplicity.test.cpp )
add_cpp_test( dryad.format.endf.createLegendreAngularDistribution                       dryad/format/endf/createLegendreAngularDistribution.test.cpp )
add_cpp_test( dryad.format.endf.createLegendreAngularDistributions                      dryad/format/endf/createLegendreAngularDistributions.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedAngularDistribution                      dryad/format/endf/createTabulatedAngularDistribution.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedAngularDistributions                     dryad/format/endf/createTabulatedAngularDistributions.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedEnergyDistribution                       dryad/format/endf/createTabulatedEnergyDistribution.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedEnergyDistributions                      dryad/format/endf/createTabulatedEnergyDistributions.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedAverageEnergy                            dryad/format/endf/createTabulatedAverageEnergy.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedFormFactor                               dryad/format/endf/createTabulatedFormFactor.test.cpp )
add_cpp_test( dryad.format.endf.createTabulatedScatteringFunction                       dryad/format/endf/createTabulatedScatteringFunction.test.cpp )
add_cpp_test( dryad.format.endf.createReactionProduct                                   dryad/format/endf/createReactionProduct.test.cpp )
add_cpp_test( dryad.format.endf.createReactionProducts                                  dryad/format/endf/createReactionProducts.test.cpp )
add_cpp_test( dryad.format.endf.createReaction                                          dryad/format/endf/createReaction.test.cpp )
add_cpp_test( dryad.format.endf.createReactions                                         dryad/format/endf/createReactions.test.cpp )
add_cpp_test( dryad.format.endf.createDocumentation                                     dryad/format/endf/createDocumentation.test.cpp )
add_cpp_test( dryad.format.endf.createProjectileTarget                                  dryad/format/endf/createProjectileTarget.test.cpp )
add_cpp_test( dryad.format.endf.createProjectileTargetFromFile                          dryad/format/endf/createProjectileTargetFromFile.test.cpp )
add_cpp_test( dryad.format.endf.createAtomicRelaxation                                  dryad/format/endf/createAtomicRelaxation.test.cpp )
add_cpp_test( dryad.format.endf.createAtomicRelaxationFromFile                          dryad/format/endf/createAtomicRelaxationFromFile.test.cpp )
add_cpp_test( dryad.format.endf.createThermalScattering                                 dryad/format/endf/createThermalScattering.test.cpp )
add_cpp_test( dryad.format.endf.createThermalScatteringFromFile                         dryad/format/endf/createThermalScatteringFromFile.test.cpp )

add_cpp_test( dryad.format.endf.createEndfIndex                                         dryad/format/endf/createEndfIndex.test.cpp )
add_cpp_test( dryad.format.endf.createEndfBoundaries                                    dryad/format/endf/createEndfBoundaries.test.cpp )
add_cpp_test( dryad.format.endf.createEndfInterpolant                                   dryad/format/endf/createEndfInterpolant.test.cpp )
add_cpp_test( dryad.format.endf.createEndfInterpolants                                  dryad/format/endf/createEndfInterpolants.test.cpp )
add_cpp_test( dryad.format.endf.createEndfSublibraryType                                dryad/format/endf/createEndfSublibraryType.test.cpp )
add_cpp_test( dryad.format.endf.atomic.createEndfSubshellDesignator                     dryad/format/endf/atomic/createEndfSubshellDesignator.test.cpp )
add_cpp_test( dryad.format.endf.atomic.createEndfSubshellData                           dryad/format/endf/atomic/createEndfSubshellData.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createEndfParticlePairs                 dryad/format/endf/resonances/lrf7/createEndfParticlePairs.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createEndfResonanceChannels             dryad/format/endf/resonances/lrf7/createEndfResonanceChannels.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createEndfResonanceParameters           dryad/format/endf/resonances/lrf7/createEndfResonanceParameters.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createEndfBackgroundChannels            dryad/format/endf/resonances/lrf7/createEndfBackgroundChannels.test.cpp )
add_cpp_test( dryad.format.endf.resonances.lrf7.createEndfRMatrixLimited                dryad/format/endf/resonances/lrf7/createEndfRMatrixLimited.test.cpp )
add_cpp_test( dryad.format.endf.thermal.createEndfIncoherentElastic                     dryad/format/endf/thermal/createEndfIncoherentElastic.test.cpp )
add_cpp_test( dryad.format.endf.thermal.createEndfCoherentElastic                       dryad/format/endf/thermal/createEndfCoherentElastic.test.cpp )
add_cpp_test( dryad.format.endf.createEndfFile2Section151                               dryad/format/endf/createEndfFile2Section151.test.cpp )
add_cpp_test( dryad.format.endf.createEndfFile3Section                                  dryad/format/endf/createEndfFile3Section.test.cpp )
add_cpp_test( dryad.format.endf.createEndfFile23Section                                 dryad/format/endf/createEndfFile23Section.test.cpp )
add_cpp_test( dryad.format.endf.createAtomicRelaxationEndfFile                          dryad/format/endf/createAtomicRelaxationEndfFile.test.cpp )
add_cpp_test( dryad.format.endf.createProjectileTargetEndfFile                          dryad/format/endf/createProjectileTargetEndfFile.test.cpp )
add_cpp_test( dryad.format.endf.createThermalScatteringEndfFile                         dryad/format/endf/createThermalScatteringEndfFile.test.cpp )

add_cpp_test( dryad.format.gendf.covariance.createCrossSectionCovarianceMatrix          dryad/format/gendf/covariance/createCrossSectionCovarianceMatrix.test.cpp )
add_cpp_test( dryad.format.gendf.covariance.createCrossSectionCovarianceData            dryad/format/gendf/covariance/createCrossSectionCovarianceData.test.cpp )
add_cpp_test( dryad.format.gendf.covariance.createCrossSectionCovarianceDataFromFile    dryad/format/gendf/covariance/createCrossSectionCovarianceDataFromFile.test.cpp )

add_cpp_test( dryad.format.gnds.convertEnergy                                           dryad/format/gnds/convertEnergy.test.cpp )
add_cpp_test( dryad.format.gnds.convertEnergies                                         dryad/format/gnds/convertEnergies.test.cpp )
add_cpp_test( dryad.format.gnds.convertCrossSection                                     dryad/format/gnds/convertCrossSection.test.cpp )
add_cpp_test( dryad.format.gnds.convertCrossSections                                    dryad/format/gnds/convertCrossSections.test.cpp )
add_cpp_test( dryad.format.gnds.convertInverseEnergy                                    dryad/format/gnds/convertInverseEnergy.test.cpp )
add_cpp_test( dryad.format.gnds.convertInverseEnergySquared                             dryad/format/gnds/convertInverseEnergySquared.test.cpp )
add_cpp_test( dryad.format.gnds.convertInverseEnergies                                  dryad/format/gnds/convertInverseEnergies.test.cpp )
add_cpp_test( dryad.format.gnds.convertInverseLengths                                   dryad/format/gnds/convertInverseLengths.test.cpp )
add_cpp_test( dryad.format.gnds.convertMass                                             dryad/format/gnds/convertMass.test.cpp )
add_cpp_test( dryad.format.gnds.convertVarianceScalingFactors                           dryad/format/gnds/convertVarianceScalingFactors.test.cpp )
add_cpp_test( dryad.format.gnds.convertRadius                                           dryad/format/gnds/convertRadius.test.cpp )
add_cpp_test( dryad.format.gnds.convertRadii                                            dryad/format/gnds/convertRadii.test.cpp )
add_cpp_test( dryad.format.gnds.convertTemperature                                      dryad/format/gnds/convertTemperature.test.cpp )
add_cpp_test( dryad.format.gnds.convertTemperatures                                     dryad/format/gnds/convertTemperatures.test.cpp )
add_cpp_test( dryad.format.gnds.createInteractionType                                   dryad/format/gnds/createInteractionType.test.cpp )
add_cpp_test( dryad.format.gnds.createInterpolationType                                 dryad/format/gnds/createInterpolationType.test.cpp )
add_cpp_test( dryad.format.gnds.createReferenceFrame                                    dryad/format/gnds/createReferenceFrame.test.cpp )
add_cpp_test( dryad.format.gnds.createStorageOrder                                      dryad/format/gnds/createStorageOrder.test.cpp )
add_cpp_test( dryad.format.gnds.createParticleIdentifier                                dryad/format/gnds/createParticleIdentifier.test.cpp )
add_cpp_test( dryad.format.gnds.readShape                                               dryad/format/gnds/readShape.test.cpp )
add_cpp_test( dryad.format.gnds.resolveLink                                             dryad/format/gnds/resolveLink.test.cpp )
add_cpp_test( dryad.format.gnds.readDouble                                              dryad/format/gnds/readDouble.test.cpp )
add_cpp_test( dryad.format.gnds.readInteger                                             dryad/format/gnds/readInteger.test.cpp )
add_cpp_test( dryad.format.gnds.readFraction                                            dryad/format/gnds/readFraction.test.cpp )
add_cpp_test( dryad.format.gnds.readFractionFromString                                  dryad/format/gnds/readFractionFromString.test.cpp )
add_cpp_test( dryad.format.gnds.readString                                              dryad/format/gnds/readString.test.cpp )
add_cpp_test( dryad.format.gnds.readAxis                                                dryad/format/gnds/readAxis.test.cpp )
add_cpp_test( dryad.format.gnds.readGrid                                                dryad/format/gnds/readGrid.test.cpp )
add_cpp_test( dryad.format.gnds.readAxes                                                dryad/format/gnds/readAxes.test.cpp )
add_cpp_test( dryad.format.gnds.readValues                                              dryad/format/gnds/readValues.test.cpp )
add_cpp_test( dryad.format.gnds.readConstant1d                                          dryad/format/gnds/readConstant1d.test.cpp )
add_cpp_test( dryad.format.gnds.readLegendre                                            dryad/format/gnds/readLegendre.test.cpp )
add_cpp_test( dryad.format.gnds.readPolynomial1d                                        dryad/format/gnds/readPolynomial1d.test.cpp )
add_cpp_test( dryad.format.gnds.readXYs1d                                               dryad/format/gnds/readXYs1d.test.cpp )
add_cpp_test( dryad.format.gnds.readArray                                               dryad/format/gnds/readArray.test.cpp )
add_cpp_test( dryad.format.gnds.readColumn                                              dryad/format/gnds/readColumn.test.cpp )
add_cpp_test( dryad.format.gnds.readColumnHeaders                                       dryad/format/gnds/readColumnHeaders.test.cpp )
add_cpp_test( dryad.format.gnds.readData                                                dryad/format/gnds/readData.test.cpp )
add_cpp_test( dryad.format.gnds.readTable                                               dryad/format/gnds/readTable.test.cpp )
add_cpp_test( dryad.format.gnds.pops.createMass                                         dryad/format/gnds/pops/createMass.test.cpp )
add_cpp_test( dryad.format.gnds.pops.createEnergy                                       dryad/format/gnds/pops/createEnergy.test.cpp )
add_cpp_test( dryad.format.gnds.pops.createSpin                                         dryad/format/gnds/pops/createSpin.test.cpp )
add_cpp_test( dryad.format.gnds.pops.createParity                                       dryad/format/gnds/pops/createParity.test.cpp )
add_cpp_test( dryad.format.gnds.pops.createParticle                                     dryad/format/gnds/pops/createParticle.test.cpp )
add_cpp_test( dryad.format.gnds.pops.createParticleDatabase                             dryad/format/gnds/pops/createParticleDatabase.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.createTabulatedRadius                        dryad/format/gnds/resonances/createTabulatedRadius.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.createRadius                                 dryad/format/gnds/resonances/createRadius.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.createParticles                              dryad/format/gnds/resonances/createParticles.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.rmatrix.createBoundaryCondition              dryad/format/gnds/resonances/rmatrix/createBoundaryCondition.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.rmatrix.createFormalism                      dryad/format/gnds/resonances/rmatrix/createFormalism.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.rmatrix.createBackground                     dryad/format/gnds/resonances/rmatrix/createBackground.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.rmatrix.createResonanceReaction              dryad/format/gnds/resonances/rmatrix/createResonanceReaction.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.rmatrix.createResonanceReactions             dryad/format/gnds/resonances/rmatrix/createResonanceReactions.test.cpp )
add_cpp_test( dryad.format.gnds.resonances.rmatrix.createCompoundSystem                 dryad/format/gnds/resonances/rmatrix/createCompoundSystem.test.cpp )
add_cpp_test( dryad.format.gnds.thermal.createDebyeWallerIntegralData                   dryad/format/gnds/thermal/createDebyeWallerIntegralData.test.cpp )
add_cpp_test( dryad.format.gnds.thermal.createCoherentElasticScattering                 dryad/format/gnds/thermal/createCoherentElasticScattering.test.cpp )
add_cpp_test( dryad.format.gnds.thermal.createIncoherentElasticScattering               dryad/format/gnds/thermal/createIncoherentElasticScattering.test.cpp )
add_cpp_test( dryad.format.gnds.readCovarianceMatrix                                    dryad/format/gnds/readCovarianceMatrix.test.cpp )
add_cpp_test( dryad.format.gnds.createPolynomialMultiplicity                            dryad/format/gnds/createPolynomialMultiplicity.test.cpp )
add_cpp_test( dryad.format.gnds.createTabulatedMultiplicity                             dryad/format/gnds/createTabulatedMultiplicity.test.cpp )
add_cpp_test( dryad.format.gnds.createTabulatedFormFactorFromNodes                      dryad/format/gnds/createTabulatedFormFactorFromNodes.test.cpp )
add_cpp_test( dryad.format.gnds.createTabulatedScatteringFunctionFromNodes              dryad/format/gnds/createTabulatedScatteringFunctionFromNodes.test.cpp )
add_cpp_test( dryad.format.gnds.createTabulatedCrossSection                             dryad/format/gnds/createTabulatedCrossSection.test.cpp )
add_cpp_test( dryad.format.gnds.createMultiplicity                                      dryad/format/gnds/createMultiplicity.test.cpp )
add_cpp_test( dryad.format.gnds.createQValue                                            dryad/format/gnds/createQValue.test.cpp )
add_cpp_test( dryad.format.gnds.createCoherentDistributionData                          dryad/format/gnds/createCoherentDistributionData.test.cpp )
add_cpp_test( dryad.format.gnds.createIncoherentDistributionData                        dryad/format/gnds/createIncoherentDistributionData.test.cpp )
add_cpp_test( dryad.format.gnds.createUncorrelatedDistributionData                      dryad/format/gnds/createUncorrelatedDistributionData.test.cpp )
add_cpp_test( dryad.format.gnds.createTwoBodyDistributionData                           dryad/format/gnds/createTwoBodyDistributionData.test.cpp )
add_cpp_test( dryad.format.gnds.createLegendreAngularDistribution                       dryad/format/gnds/createLegendreAngularDistribution.test.cpp )
add_cpp_test( dryad.format.gnds.createTabulatedAngularDistribution                      dryad/format/gnds/createTabulatedAngularDistribution.test.cpp )
add_cpp_test( dryad.format.gnds.createTabulatedEnergyDistribution                       dryad/format/gnds/createTabulatedEnergyDistribution.test.cpp )
add_cpp_test( dryad.format.gnds.createTabulatedAverageEnergy                            dryad/format/gnds/createTabulatedAverageEnergy.test.cpp )
add_cpp_test( dryad.format.gnds.createReaction                                          dryad/format/gnds/createReaction.test.cpp )
add_cpp_test( dryad.format.gnds.createReactions                                         dryad/format/gnds/createReactions.test.cpp )
add_cpp_test( dryad.format.gnds.atomic.createElectronSubshellConfiguration              dryad/format/gnds/atomic/createElectronSubshellConfiguration.test.cpp )
add_cpp_test( dryad.format.gnds.covariance.createScalingType                            dryad/format/gnds/covariance/createScalingType.test.cpp )
add_cpp_test( dryad.format.gnds.covariance.createVarianceScaling                        dryad/format/gnds/covariance/createVarianceScaling.test.cpp )
add_cpp_test( dryad.format.gnds.covariance.createCrossSectionCovarianceMatrix           dryad/format/gnds/covariance/createCrossSectionCovarianceMatrix.test.cpp )
add_cpp_test( dryad.format.gnds.covariance.createCovarianceData                         dryad/format/gnds/covariance/createCovarianceData.test.cpp )
add_cpp_test( dryad.format.gnds.createProjectileTarget                                  dryad/format/gnds/createProjectileTarget.test.cpp )
add_cpp_test( dryad.format.gnds.createProjectileTargetFromFile                          dryad/format/gnds/createProjectileTargetFromFile.test.cpp )
add_cpp_test( dryad.format.gnds.createAtomicRelaxation                                  dryad/format/gnds/createAtomicRelaxation.test.cpp )
add_cpp_test( dryad.format.gnds.createAtomicRelaxationFromFile                          dryad/format/gnds/createAtomicRelaxationFromFile.test.cpp )
add_cpp_test( dryad.format.gnds.createThermalScattering                                 dryad/format/gnds/createThermalScattering.test.cpp )
add_cpp_test( dryad.format.gnds.createThermalScatteringFromFile                         dryad/format/endf/createThermalScatteringFromFile.test.cpp )

add_cpp_test( dryad.external.ComptonProfiles                                            dryad/external/ComptonProfiles.test.cpp )
add_cpp_test( dryad.external.KleinNishina                                               dryad/external/KleinNishina.test.cpp )
add_cpp_test( dryad.external.ripl3.LevelEntry                                           dryad/external/ripl3/LevelEntry.test.cpp )
add_cpp_test( dryad.external.ripl3.Levels                                               dryad/external/ripl3/Levels.test.cpp )

# psychic tests

add_cpp_test( psychic.TestStatus                                                        psychic/TestStatus.test.cpp )
add_cpp_test( psychic.covariance.PositiveSemiDefinite                                   psychic/covariance/PositiveSemiDefinite.test.cpp )
add_cpp_test( psychic.covariance.PositiveVariances                                      psychic/covariance/PositiveVariances.test.cpp )
add_cpp_test( psychic.covariance.EigenvalueRatio                                        psychic/covariance/EigenvalueRatio.test.cpp )
add_cpp_test( psychic.covariance.BoundedCorrelations                                    psychic/covariance/BoundedCorrelations.test.cpp )
add_cpp_test( psychic.covariance.DiagonalCorrelations                                   psychic/covariance/DiagonalCorrelations.test.cpp )
add_cpp_test( psychic.covariance.TestSuite                                              psychic/covariance/TestSuite.test.cpp )

# reconr tests

add_cpp_test( reconr.unioniseCrossSections                                              reconr/unioniseCrossSections.test.cpp )
add_cpp_test( reconr.calculateSummationCrossSections                                    reconr/calculateSummationCrossSections.test.cpp )

# medic tests

add_cpp_test( medic.pruneCrossSection                                                   medic/pruneCrossSection.test.cpp )
add_cpp_test( medic.pruneCrossSections                                                  medic/pruneCrossSections.test.cpp )
add_cpp_test( medic.covariance.pruneSmallEigenvalues                                    medic/covariance/pruneSmallEigenvalues.test.cpp )

# acer tests

add_cpp_test( acer.processElectronPhotonRelaxation                                      acer/processElectronPhotonRelaxation.test.cpp )
