#######################################################################
# Setup
#######################################################################

enable_testing()

FetchContent_MakeAvailable( Catch2 )

function( add_cpp_test name source )

  set( test_name "njoy.${name}.test" )
  add_executable( ${test_name} ${source} )
  add_test( NAME ${test_name} COMMAND ${test_name} )
  target_link_libraries( ${test_name} PRIVATE njoy )
  target_link_libraries( ${test_name} PRIVATE Catch2::Catch2WithMain )

  file( GLOB resources "resources/*" )
  foreach( resource ${resources} )
    file( COPY "${resource}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}" )
  endforeach()

endfunction()

#######################################################################
# Unit testing directories
#######################################################################

message( STATUS "Adding njoy C++ unit testing" )

# njoy tests

add_cpp_test( configuration                                                                  configuration.test.cpp )
add_cpp_test( matrix                                                                         matrix.test.cpp )

# utility tests

add_cpp_test( utility.find_closest                                                           utility/find_closest.test.cpp )

# dryad tests

add_cpp_test( dryad.base.UniformDistribution                                                 dryad/base/UniformDistribution.test.cpp )

add_cpp_test( dryad.atomic.ElectronSubshellConfiguration                                     dryad/atomic/ElectronSubshellConfiguration.test.cpp )
add_cpp_test( dryad.atomic.NonRadiativeTransitionData                                        dryad/atomic/NonRadiativeTransitionData.test.cpp )
add_cpp_test( dryad.atomic.RadiativeTransitionData                                           dryad/atomic/RadiativeTransitionData.test.cpp )

add_cpp_test( dryad.covariance.base.Metadata                                                 dryad/covariance/base/Metadata.test.cpp )
add_cpp_test( dryad.covariance.base.CovarianceMatrix                                         dryad/covariance/base/CovarianceMatrix.test.cpp )
add_cpp_test( dryad.covariance.VarianceScaling                                               dryad/covariance/VarianceScaling.test.cpp )
add_cpp_test( dryad.covariance.CrossSectionMetadata                                          dryad/covariance/CrossSectionMetadata.test.cpp )
add_cpp_test( dryad.covariance.CrossSectionCovarianceMatrix                                  dryad/covariance/CrossSectionCovarianceMatrix.test.cpp )
add_cpp_test( dryad.covariance.AngularDistributionMetadata                                   dryad/covariance/AngularDistributionMetadata.test.cpp )
add_cpp_test( dryad.covariance.AngularDistributionCovarianceMatrix                           dryad/covariance/AngularDistributionCovarianceMatrix.test.cpp )
add_cpp_test( dryad.covariance.AngularDistributionCovarianceData                             dryad/covariance/AngularDistributionCovarianceData.test.cpp )
add_cpp_test( dryad.covariance.ProductMultiplicityMetadata                                   dryad/covariance/ProductMultiplicityMetadata.test.cpp )
add_cpp_test( dryad.covariance.ProductMultiplicityCovarianceMatrix                           dryad/covariance/ProductMultiplicityCovarianceMatrix.test.cpp )
add_cpp_test( dryad.covariance.LinearCombinationCovariance                                   dryad/covariance/LinearCombinationCovariance.test.cpp )
add_cpp_test( dryad.covariance.CrossSectionCovarianceData                                    dryad/covariance/CrossSectionCovarianceData.test.cpp )
add_cpp_test( dryad.covariance.CovarianceData                                                dryad/covariance/CovarianceData.test.cpp )

add_cpp_test( dryad.id.EnergyGroup                                                           dryad/id/EnergyGroup.test.cpp )
add_cpp_test( dryad.id.ElectronSubshellID                                                    dryad/id/ElectronSubshellID.test.cpp )
add_cpp_test( dryad.id.ElementID                                                             dryad/id/ElementID.test.cpp )
add_cpp_test( dryad.id.LevelID                                                               dryad/id/LevelID.test.cpp )
add_cpp_test( dryad.id.ParticleID                                                            dryad/id/ParticleID.test.cpp )
add_cpp_test( dryad.id.ReactionType                                                          dryad/id/ReactionType.test.cpp )
add_cpp_test( dryad.id.ReactionID                                                            dryad/id/ReactionID.test.cpp )
add_cpp_test( dryad.id.ChannelID                                                             dryad/id/ChannelID.test.cpp )

add_cpp_test( dryad.resonances.ParticlePair                                                  dryad/resonances/ParticlePair.test.cpp )
add_cpp_test( dryad.resonances.TabulatedRadius                                               dryad/resonances/TabulatedRadius.test.cpp )
add_cpp_test( dryad.resonances.ChannelRadii                                                  dryad/resonances/ChannelRadii.test.cpp )
add_cpp_test( dryad.resonances.ChannelQuantumNumbers                                         dryad/resonances/ChannelQuantumNumbers.test.cpp )
add_cpp_test( dryad.resonances.HardSpherePenetrability                                       dryad/resonances/HardSpherePenetrability.test.cpp )
add_cpp_test( dryad.resonances.HardSphereShiftFactor                                         dryad/resonances/HardSphereShiftFactor.test.cpp )
add_cpp_test( dryad.resonances.HardSpherePhaseShift                                          dryad/resonances/HardSpherePhaseShift.test.cpp )
add_cpp_test( dryad.resonances.CoulombPenetrability                                          dryad/resonances/CoulombPenetrability.test.cpp )
add_cpp_test( dryad.resonances.CoulombShiftFactor                                            dryad/resonances/CoulombShiftFactor.test.cpp )
add_cpp_test( dryad.resonances.CoulombPhaseShift                                             dryad/resonances/CoulombPhaseShift.test.cpp )
add_cpp_test( dryad.resonances.CoulombPhaseShiftDifference                                   dryad/resonances/CoulombPhaseShiftDifference.test.cpp )
add_cpp_test( dryad.resonances.TabulatedWaveFunction                                         dryad/resonances/TabulatedWaveFunction.test.cpp )
add_cpp_test( dryad.resonances.FrohnerBackground                                             dryad/resonances/FrohnerBackground.test.cpp )
add_cpp_test( dryad.resonances.SammyBackground                                               dryad/resonances/SammyBackground.test.cpp )
add_cpp_test( dryad.resonances.TabulatedBackground                                           dryad/resonances/TabulatedBackground.test.cpp )
add_cpp_test( dryad.resonances.Channel                                                       dryad/resonances/Channel.test.cpp )
add_cpp_test( dryad.resonances.ResonanceTable                                                dryad/resonances/ResonanceTable.test.cpp )
add_cpp_test( dryad.resonances.calculator.Constant                                           dryad/resonances/calculator/Constant.test.cpp )
add_cpp_test( dryad.resonances.calculator.ShiftFactor                                        dryad/resonances/calculator/ShiftFactor.test.cpp )
add_cpp_test( dryad.resonances.calculator.ReichMoore                                         dryad/resonances/calculator/ReichMoore.test.cpp )
add_cpp_test( dryad.resonances.SpinGroup                                                     dryad/resonances/SpinGroup.test.cpp )
add_cpp_test( dryad.resonances.CompoundSystem                                                dryad/resonances/CompoundSystem.test.cpp )
add_cpp_test( dryad.resonances.TabulatedLevelSpacing                                         dryad/resonances/TabulatedLevelSpacing.test.cpp )
add_cpp_test( dryad.resonances.TabulatedAverageWidths                                        dryad/resonances/TabulatedAverageWidths.test.cpp )
add_cpp_test( dryad.resonances.UnresolvedResonanceTable                                      dryad/resonances/UnresolvedResonanceTable.test.cpp )
add_cpp_test( dryad.resonances.UnresolvedChannel                                             dryad/resonances/UnresolvedChannel.test.cpp )
add_cpp_test( dryad.resonances.UnresolvedSpinGroup                                           dryad/resonances/UnresolvedSpinGroup.test.cpp )
add_cpp_test( dryad.resonances.UnresolvedCompoundSystem                                      dryad/resonances/UnresolvedCompoundSystem.test.cpp)

add_cpp_test( dryad.thermal.ShortCollisionTimeScatteringKernel                               dryad/thermal/ShortCollisionTimeScatteringKernel.test.cpp )
add_cpp_test( dryad.thermal.TabulatedScatteringKernelFunction                                dryad/thermal/TabulatedScatteringKernelFunction.test.cpp )
add_cpp_test( dryad.thermal.TabulatedScatteringKernel                                        dryad/thermal/TabulatedScatteringKernel.test.cpp )
add_cpp_test( dryad.thermal.ScatteringKernel                                                 dryad/thermal/ScatteringKernel.test.cpp )
add_cpp_test( dryad.thermal.BraggEdgeData                                                    dryad/thermal/BraggEdgeData.test.cpp )
add_cpp_test( dryad.thermal.DebyeWallerIntegralData                                          dryad/thermal/DebyeWallerIntegralData.test.cpp )
add_cpp_test( dryad.thermal.CoherentElasticScattering                                        dryad/thermal/CoherentElasticScattering.test.cpp )
add_cpp_test( dryad.thermal.IncoherentElasticCrossSection                                    dryad/thermal/IncoherentElasticCrossSection.test.cpp )
add_cpp_test( dryad.thermal.IncoherentElasticAngularPdf                                      dryad/thermal/IncoherentElasticAngularPdf.test.cpp )
add_cpp_test( dryad.thermal.IncoherentElasticAngularCdf                                      dryad/thermal/IncoherentElasticAngularCdf.test.cpp )
add_cpp_test( dryad.thermal.IncoherentElasticAngularDistribution                             dryad/thermal/IncoherentElasticAngularDistribution.test.cpp )
add_cpp_test( dryad.thermal.IncoherentElasticScattering                                      dryad/thermal/IncoherentElasticScattering.test.cpp )
add_cpp_test( dryad.thermal.IncoherentInelasticScattering                                    dryad/thermal/IncoherentInelasticScattering.test.cpp )

add_cpp_test( dryad.Documentation                                                            dryad/Documentation.test.cpp )

add_cpp_test( dryad.Particle                                                                 dryad/Particle.test.cpp )
add_cpp_test( dryad.ParticleDatabase                                                         dryad/ParticleDatabase.test.cpp )

add_cpp_test( dryad.CoherentDistributionData                                                 dryad/CoherentDistributionData.test.cpp )
add_cpp_test( dryad.IncoherentDistributionData                                               dryad/IncoherentDistributionData.test.cpp )

add_cpp_test( dryad.MultigroupMultiplicity                                                   dryad/MultigroupMultiplicity.test.cpp )
add_cpp_test( dryad.MultigroupCrossSection                                                   dryad/MultigroupCrossSection.test.cpp )
add_cpp_test( dryad.MultigroupAverageCosine                                                  dryad/MultigroupAverageCosine.test.cpp )
add_cpp_test( dryad.MultigroupAverageEnergy                                                  dryad/MultigroupAverageEnergy.test.cpp )
add_cpp_test( dryad.MultigroupReactionProduct                                                dryad/MultigroupReactionProduct.test.cpp )
add_cpp_test( dryad.MultigroupReaction                                                       dryad/MultigroupReaction.test.cpp )

add_cpp_test( dryad.TabulatedFormFactor                                                      dryad/TabulatedFormFactor.test.cpp )
add_cpp_test( dryad.TabulatedScatteringFunction                                              dryad/TabulatedScatteringFunction.test.cpp )
add_cpp_test( dryad.PolynomialMultiplicity                                                   dryad/PolynomialMultiplicity.test.cpp )
add_cpp_test( dryad.TabulatedMultiplicity                                                    dryad/TabulatedMultiplicity.test.cpp )
add_cpp_test( dryad.TabulatedAverageCosine                                                   dryad/TabulatedAverageCosine.test.cpp )
add_cpp_test( dryad.TabulatedAverageEnergy                                                   dryad/TabulatedAverageEnergy.test.cpp )
add_cpp_test( dryad.IsotropicAngularDistributionFunction                                     dryad/IsotropicAngularDistributionFunction.test.cpp )
add_cpp_test( dryad.LegendreAngularDistributionFunction                                      dryad/LegendreAngularDistributionFunction.test.cpp )
add_cpp_test( dryad.LegendreAngularDistribution                                              dryad/LegendreAngularDistribution.test.cpp )
add_cpp_test( dryad.LegendreAngularDistributions                                             dryad/LegendreAngularDistributions.test.cpp )
add_cpp_test( dryad.TabulatedAngularDistributionFunction                                     dryad/TabulatedAngularDistributionFunction.test.cpp )
add_cpp_test( dryad.TabulatedAngularDistribution                                             dryad/TabulatedAngularDistribution.test.cpp )
add_cpp_test( dryad.TabulatedAngularDistributions                                            dryad/TabulatedAngularDistributions.test.cpp )
add_cpp_test( dryad.MixedAngularDistribution                                                 dryad/MixedAngularDistribution.test.cpp )
add_cpp_test( dryad.MixedAngularDistributions                                                dryad/MixedAngularDistributions.test.cpp )
add_cpp_test( dryad.TabulatedComptonProfile                                                  dryad/TabulatedComptonProfile.test.cpp )
add_cpp_test( dryad.TabulatedComptonProfileFunction                                          dryad/TabulatedComptonProfileFunction.test.cpp )
add_cpp_test( dryad.UniformAngularDistribution                                               dryad/UniformAngularDistribution.test.cpp )
add_cpp_test( dryad.UniformAngularDistributions                                              dryad/UniformAngularDistributions.test.cpp )
add_cpp_test( dryad.UniformEnergyDistribution                                                dryad/UniformEnergyDistribution.test.cpp )
add_cpp_test( dryad.UniformEnergyDistributions                                               dryad/UniformEnergyDistributions.test.cpp )
add_cpp_test( dryad.TabulatedEnergyDistributionFunction                                      dryad/TabulatedEnergyDistributionFunction.test.cpp )
add_cpp_test( dryad.TabulatedEnergyDistribution                                              dryad/TabulatedEnergyDistribution.test.cpp )
add_cpp_test( dryad.TabulatedEnergyDistributions                                             dryad/TabulatedEnergyDistributions.test.cpp )
add_cpp_test( dryad.TwoBodyDistributionData                                                  dryad/TwoBodyDistributionData.test.cpp )
add_cpp_test( dryad.UncorrelatedDistributionData                                             dryad/UncorrelatedDistributionData.test.cpp )
add_cpp_test( dryad.ReactionProduct                                                          dryad/ReactionProduct.test.cpp )
add_cpp_test( dryad.TabulatedCrossSection                                                    dryad/TabulatedCrossSection.test.cpp )
add_cpp_test( dryad.Reaction                                                                 dryad/Reaction.test.cpp )

add_cpp_test( dryad.ProjectileTarget                                                         dryad/ProjectileTarget.test.cpp )
add_cpp_test( dryad.MultigroupProjectileTarget                                               dryad/MultigroupProjectileTarget.test.cpp )
add_cpp_test( dryad.AtomicRelaxation                                                         dryad/AtomicRelaxation.test.cpp )
add_cpp_test( dryad.ThermalScattering                                                        dryad/ThermalScattering.test.cpp )

add_cpp_test( format.createIndex                                                             format/createIndex.test.cpp )
add_cpp_test( format.createVector                                                            format/createVector.test.cpp )
add_cpp_test( format.adjustScatterLevel                                                      format/adjustScatterLevel.test.cpp )
add_cpp_test( format.revertScatterLevel                                                      format/revertScatterLevel.test.cpp )
add_cpp_test( format.collectParticleIdentifiers                                              format/collectParticleIdentifiers.test.cpp )
add_cpp_test( format.convertLegendreMoments                                                  format/convertLegendreMoments.test.cpp )

add_cpp_test( format.ace.read.createProjectileIdentifier                                     format/ace/read/createProjectileIdentifier.test.cpp )
add_cpp_test( format.ace.read.createTabulatedScatteringFunction                              format/ace/read/createTabulatedScatteringFunction.test.cpp )
add_cpp_test( format.ace.read.createTabulatedAngularDistributionFunction                     format/ace/read/createTabulatedAngularDistributionFunction.test.cpp )
add_cpp_test( format.ace.read.createTabulatedEnergyDistributionFunction                      format/ace/read/createTabulatedEnergyDistributionFunction.test.cpp )
add_cpp_test( format.ace.read.continuous.createTabulatedCrossSection                         format/ace/read/continuous/createTabulatedCrossSection.test.cpp )
add_cpp_test( format.ace.read.continuous.createElasticTabulatedCrossSection                  format/ace/read/continuous/createElasticTabulatedCrossSection.test.cpp )
add_cpp_test( format.ace.read.continuous.createTotalTabulatedCrossSection                    format/ace/read/continuous/createTotalTabulatedCrossSection.test.cpp )
add_cpp_test( format.ace.read.continuous.createReaction                                      format/ace/read/continuous/createReaction.test.cpp )
add_cpp_test( format.ace.read.continuous.createReactions                                     format/ace/read/continuous/createReactions.test.cpp )
add_cpp_test( format.ace.read.photonuclear.createReaction                                    format/ace/read/photonuclear/createReaction.test.cpp )
add_cpp_test( format.ace.read.photonuclear.createReactions                                   format/ace/read/photonuclear/createReactions.test.cpp )
add_cpp_test( format.ace.read.photonuclear.createProjectileTarget                            format/ace/read/photonuclear/createProjectileTarget.test.cpp )
add_cpp_test( format.ace.read.electroatomic.createPdfFromCdf                                 format/ace/read/electroatomic/createPdfFromCdf.test.cpp )
add_cpp_test( format.ace.read.electroatomic.createReactionIdentifiers                        format/ace/read/electroatomic/createReactionIdentifiers.test.cpp )
add_cpp_test( format.ace.read.electroatomic.createPartialReactionIdentifiers                 format/ace/read/electroatomic/createPartialReactionIdentifiers.test.cpp )
add_cpp_test( format.ace.read.electroatomic.createTabulatedCrossSections                     format/ace/read/electroatomic/createTabulatedCrossSections.test.cpp )
add_cpp_test( format.ace.read.electroatomic.createReactions                                  format/ace/read/electroatomic/createReactions.test.cpp )
add_cpp_test( format.ace.read.electroatomic.createProjectileTarget                           format/ace/read/electroatomic/createProjectileTarget.test.cpp )
add_cpp_test( format.ace.read.photoatomic.createReactionIdentifiers                          format/ace/read/photoatomic/createReactionIdentifiers.test.cpp )
add_cpp_test( format.ace.read.photoatomic.createTabulatedComptonProfile                      format/ace/read/photoatomic/createTabulatedComptonProfile.test.cpp )
add_cpp_test( format.ace.read.photoatomic.createTabulatedComptonProfiles                     format/ace/read/photoatomic/createTabulatedComptonProfiles.test.cpp )
add_cpp_test( format.ace.read.photoatomic.createPartialReactionIdentifiers                   format/ace/read/photoatomic/createPartialReactionIdentifiers.test.cpp )
add_cpp_test( format.ace.read.photoatomic.createTabulatedCrossSections                       format/ace/read/photoatomic/createTabulatedCrossSections.test.cpp )
add_cpp_test( format.ace.read.photoatomic.createReactionProducts                             format/ace/read/photoatomic/createReactionProducts.test.cpp )
add_cpp_test( format.ace.read.photoatomic.createReactions                                    format/ace/read/photoatomic/createReactions.test.cpp )
add_cpp_test( format.ace.read.createParticleDatabase                                         format/ace/read/createParticleDatabase.test.cpp )
add_cpp_test( format.ace.read.photoatomic.createProjectileTarget                             format/ace/read/photoatomic/createProjectileTarget.test.cpp )
add_cpp_test( format.ace.read.continuous.createProjectileTarget                              format/ace/read/continuous/createProjectileTarget.test.cpp )
add_cpp_test( format.ace.read.createProjectileTargetFromFile                                 format/ace/read/createProjectileTargetFromFile.test.cpp )

add_cpp_test( format.ace.write.atomic.createSubshellTransitionDataBlock                      format/ace/write/atomic/createSubshellTransitionDataBlock.test.cpp )
add_cpp_test( format.ace.write.atomic.createElectronShellBlock                               format/ace/write/atomic/createElectronShellBlock.test.cpp )
add_cpp_test( format.ace.write.atomic.createElectronSubshellBlock                            format/ace/write/atomic/createElectronSubshellBlock.test.cpp )

add_cpp_test( format.ace.write.electroatomic.createPrincipalCrossSectionBlock                format/ace/write/electroatomic/createPrincipalCrossSectionBlock.test.cpp )
add_cpp_test( format.ace.write.electroatomic.createElasticCrossSectionBlock                  format/ace/write/electroatomic/createElasticCrossSectionBlock.test.cpp )
add_cpp_test( format.ace.write.electroatomic.createElasticAngularDistributionBlock           format/ace/write/electroatomic/createElasticAngularDistributionBlock.test.cpp )
add_cpp_test( format.ace.write.electroatomic.createBremsstrahlungDistributionBlock           format/ace/write/electroatomic/createBremsstrahlungDistributionBlock.test.cpp )
add_cpp_test( format.ace.write.electroatomic.createIonisationDistributionBlocks              format/ace/write/electroatomic/createIonisationDistributionBlocks.test.cpp )
add_cpp_test( format.ace.write.electroatomic.createExcitationBlock                           format/ace/write/electroatomic/createExcitationBlock.test.cpp )
add_cpp_test( format.ace.write.electroatomic.createBremsstrahlungBlock                       format/ace/write/electroatomic/createBremsstrahlungBlock.test.cpp )

add_cpp_test( format.ace.write.photoatomic.createPrincipalCrossSectionBlock                  format/ace/write/photoatomic/createPrincipalCrossSectionBlock.test.cpp )
add_cpp_test( format.ace.write.photoatomic.createPhotoelectricCrossSectionBlock              format/ace/write/photoatomic/createPhotoelectricCrossSectionBlock.test.cpp )
add_cpp_test( format.ace.write.photoatomic.createHeatingNumbersBlock                         format/ace/write/photoatomic/createHeatingNumbersBlock.test.cpp )
add_cpp_test( format.ace.write.photoatomic.createFluorescenceDataBlock                       format/ace/write/photoatomic/createFluorescenceDataBlock.test.cpp )
add_cpp_test( format.ace.write.photoatomic.createIncoherentScatteringFunctionBlock           format/ace/write/photoatomic/createIncoherentScatteringFunctionBlock.test.cpp )
add_cpp_test( format.ace.write.photoatomic.createComptonProfileBlock                         format/ace/write/photoatomic/createComptonProfileBlock.test.cpp )
add_cpp_test( format.ace.write.photoatomic.createCoherentFormFactorBlock                     format/ace/write/photoatomic/createCoherentFormFactorBlock.test.cpp )

add_cpp_test( format.endf.ReactionInformation                                                format/endf/ReactionInformation.test.cpp )
add_cpp_test( format.endf.read.createBoundaries                                              format/endf/read/createBoundaries.test.cpp )
add_cpp_test( format.endf.read.createReferenceFrame                                          format/endf/read/createReferenceFrame.test.cpp )
add_cpp_test( format.endf.read.createInterpolant                                             format/endf/read/createInterpolant.test.cpp )
add_cpp_test( format.endf.read.createInterpolants                                            format/endf/read/createInterpolants.test.cpp )
add_cpp_test( format.endf.read.createProjectileIdentifier                                    format/endf/read/createProjectileIdentifier.test.cpp )
add_cpp_test( format.endf.read.createProductIdentifier                                       format/endf/read/createProductIdentifier.test.cpp )
add_cpp_test( format.endf.read.createTargetIdentifier                                        format/endf/read/createTargetIdentifier.test.cpp )
add_cpp_test( format.endf.read.createInteractionType                                         format/endf/read/createInteractionType.test.cpp )
add_cpp_test( format.endf.read.createComplexBreakUpParticles                                 format/endf/read/createComplexBreakUpParticles.test.cpp )
add_cpp_test( format.endf.read.resonances.createTabulatedRadius                              format/endf/read/resonances/createTabulatedRadius.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf3.createSpinGroups                              format/endf/read/resonances/lrf3/createSpinGroups.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf3.createCompoundSystem                          format/endf/read/resonances/lrf3/createCompoundSystem.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createBoundaryCondition                       format/endf/read/resonances/lrf7/createBoundaryCondition.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createFormalism                               format/endf/read/resonances/lrf7/createFormalism.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createKinematics                              format/endf/read/resonances/lrf7/createKinematics.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createReactionIdentifiers                     format/endf/read/resonances/lrf7/createReactionIdentifiers.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createParticlePairs                           format/endf/read/resonances/lrf7/createParticlePairs.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createFrohnerBackground                       format/endf/read/resonances/lrf7/createFrohnerBackground.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createSammyBackground                         format/endf/read/resonances/lrf7/createSammyBackground.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createTabulatedBackground                     format/endf/read/resonances/lrf7/createTabulatedBackground.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createChannels                                format/endf/read/resonances/lrf7/createChannels.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createSpinGroups                              format/endf/read/resonances/lrf7/createSpinGroups.test.cpp )
add_cpp_test( format.endf.read.resonances.lrf7.createCompoundSystem                          format/endf/read/resonances/lrf7/createCompoundSystem.test.cpp )
add_cpp_test( format.endf.read.thermal.createBraggEdges                                      format/endf/read/thermal/createBraggEdges.test.cpp )
add_cpp_test( format.endf.read.thermal.createDebyeWallerIntegralData                         format/endf/read/thermal/createDebyeWallerIntegralData.test.cpp )
add_cpp_test( format.endf.read.thermal.createCoherentElasticScattering                       format/endf/read/thermal/createCoherentElasticScattering.test.cpp )
add_cpp_test( format.endf.read.thermal.createIncoherentElasticScattering                     format/endf/read/thermal/createIncoherentElasticScattering.test.cpp )
add_cpp_test( format.endf.read.thermal.createIncoherentInelasticScattering                   format/endf/read/thermal/createIncoherentInelasticScattering.test.cpp )
add_cpp_test( format.endf.read.atomic.createElectronSubshellID                               format/endf/read/atomic/createElectronSubshellID.test.cpp )
add_cpp_test( format.endf.read.atomic.createElectronSubshellConfiguration                    format/endf/read/atomic/createElectronSubshellConfiguration.test.cpp )
add_cpp_test( format.endf.read.covariance.createMatrix                                       format/endf/read/covariance/createMatrix.test.cpp )
add_cpp_test( format.endf.read.covariance.createVarianceScaling                              format/endf/read/covariance/createVarianceScaling.test.cpp )
add_cpp_test( format.endf.read.covariance.createCrossSectionCovarianceMatrix                 format/endf/read/covariance/createCrossSectionCovarianceMatrix.test.cpp )
add_cpp_test( format.endf.read.covariance.createCrossSectionCovarianceData                   format/endf/read/covariance/createCrossSectionCovarianceData.test.cpp )
add_cpp_test( format.endf.read.covariance.createAngularDistributionCovarianceMatrix          format/endf/read/covariance/createAngularDistributionCovarianceMatrix.test.cpp )
add_cpp_test( format.endf.read.covariance.createAngularDistributionCovarianceData            format/endf/read/covariance/createAngularDistributionCovarianceData.test.cpp )
add_cpp_test( format.endf.read.covariance.createCovarianceData                               format/endf/read/covariance/createCovarianceData.test.cpp )
add_cpp_test( format.endf.read.createTabulatedCrossSection                                   format/endf/read/createTabulatedCrossSection.test.cpp )
add_cpp_test( format.endf.read.createPolynomialMultiplicity                                  format/endf/read/createPolynomialMultiplicity.test.cpp )
add_cpp_test( format.endf.read.createTabulatedMultiplicity                                   format/endf/read/createTabulatedMultiplicity.test.cpp )
add_cpp_test( format.endf.read.createMultiplicity                                            format/endf/read/createMultiplicity.test.cpp )
add_cpp_test( format.endf.read.createLegendreAngularDistribution                             format/endf/read/createLegendreAngularDistribution.test.cpp )
add_cpp_test( format.endf.read.createLegendreAngularDistributions                            format/endf/read/createLegendreAngularDistributions.test.cpp )
add_cpp_test( format.endf.read.createTabulatedAngularDistribution                            format/endf/read/createTabulatedAngularDistribution.test.cpp )
add_cpp_test( format.endf.read.createTabulatedAngularDistributions                           format/endf/read/createTabulatedAngularDistributions.test.cpp )
add_cpp_test( format.endf.read.createMixedAngularDistribution                                format/endf/read/createMixedAngularDistribution.test.cpp )
add_cpp_test( format.endf.read.createMixedAngularDistributions                               format/endf/read/createMixedAngularDistributions.test.cpp )
add_cpp_test( format.endf.read.createTabulatedEnergyDistribution                             format/endf/read/createTabulatedEnergyDistribution.test.cpp )
add_cpp_test( format.endf.read.createTabulatedEnergyDistributions                            format/endf/read/createTabulatedEnergyDistributions.test.cpp )
add_cpp_test( format.endf.read.createTabulatedAverageEnergy                                  format/endf/read/createTabulatedAverageEnergy.test.cpp )
add_cpp_test( format.endf.read.createTabulatedFormFactor                                     format/endf/read/createTabulatedFormFactor.test.cpp )
add_cpp_test( format.endf.read.createTabulatedScatteringFunction                             format/endf/read/createTabulatedScatteringFunction.test.cpp )
add_cpp_test( format.endf.read.createReactionProduct                                         format/endf/read/createReactionProduct.test.cpp )
add_cpp_test( format.endf.read.createReactionProducts                                        format/endf/read/createReactionProducts.test.cpp )
add_cpp_test( format.endf.read.createReaction                                                format/endf/read/createReaction.test.cpp )
add_cpp_test( format.endf.read.createReactions                                               format/endf/read/createReactions.test.cpp )
add_cpp_test( format.endf.read.createDocumentation                                           format/endf/read/createDocumentation.test.cpp )
add_cpp_test( format.endf.read.createParticleDatabase                                        format/endf/read/createParticleDatabase.test.cpp )
add_cpp_test( format.endf.read.createProjectileTarget                                        format/endf/read/createProjectileTarget.test.cpp )
add_cpp_test( format.endf.read.createProjectileTargetFromFile                                format/endf/read/createProjectileTargetFromFile.test.cpp )
add_cpp_test( format.endf.read.createAtomicRelaxation                                        format/endf/read/createAtomicRelaxation.test.cpp )
add_cpp_test( format.endf.read.createAtomicRelaxationFromFile                                format/endf/read/createAtomicRelaxationFromFile.test.cpp )
add_cpp_test( format.endf.read.createThermalScattering                                       format/endf/read/createThermalScattering.test.cpp )
add_cpp_test( format.endf.read.createThermalScatteringFromFile                               format/endf/read/createThermalScatteringFromFile.test.cpp )

add_cpp_test( format.endf.write.createIndex                                                  format/endf/write/createIndex.test.cpp )
add_cpp_test( format.endf.write.createBoundaries                                             format/endf/write/createBoundaries.test.cpp )
add_cpp_test( format.endf.write.createInterpolant                                            format/endf/write/createInterpolant.test.cpp )
add_cpp_test( format.endf.write.createInterpolants                                           format/endf/write/createInterpolants.test.cpp )
add_cpp_test( format.endf.write.createSublibraryType                                         format/endf/write/createSublibraryType.test.cpp )
add_cpp_test( format.endf.write.atomic.createSubshellDesignator                              format/endf/write/atomic/createSubshellDesignator.test.cpp )
add_cpp_test( format.endf.write.atomic.createSubshellData                                    format/endf/write/atomic/createSubshellData.test.cpp )
add_cpp_test( format.endf.write.resonances.lrf7.createParticlePairs                          format/endf/write/resonances/lrf7/createParticlePairs.test.cpp )
add_cpp_test( format.endf.write.resonances.lrf7.createResonanceChannels                      format/endf/write/resonances/lrf7/createResonanceChannels.test.cpp )
add_cpp_test( format.endf.write.resonances.lrf7.createResonanceParameters                    format/endf/write/resonances/lrf7/createResonanceParameters.test.cpp )
add_cpp_test( format.endf.write.resonances.lrf7.createBackgroundChannels                     format/endf/write/resonances/lrf7/createBackgroundChannels.test.cpp )
add_cpp_test( format.endf.write.resonances.lrf7.createRMatrixLimited                         format/endf/write/resonances/lrf7/createRMatrixLimited.test.cpp )
add_cpp_test( format.endf.write.thermal.createIncoherentElastic                              format/endf/write/thermal/createIncoherentElastic.test.cpp )
add_cpp_test( format.endf.write.thermal.createCoherentElastic                                format/endf/write/thermal/createCoherentElastic.test.cpp )
add_cpp_test( format.endf.write.createFile2Section151                                        format/endf/write/createFile2Section151.test.cpp )
add_cpp_test( format.endf.write.createFile3Section                                           format/endf/write/createFile3Section.test.cpp )
add_cpp_test( format.endf.write.createFile23Section                                          format/endf/write/createFile23Section.test.cpp )
add_cpp_test( format.endf.write.createAtomicRelaxationFile                                   format/endf/write/createAtomicRelaxationFile.test.cpp )
add_cpp_test( format.endf.write.createProjectileTargetFile                                   format/endf/write/createProjectileTargetFile.test.cpp )
add_cpp_test( format.endf.write.createThermalScatteringFile                                  format/endf/write/createThermalScatteringFile.test.cpp )

add_cpp_test( format.gendf.read.covariance.createCrossSectionCovarianceMatrix                format/gendf/read/covariance/createCrossSectionCovarianceMatrix.test.cpp )
add_cpp_test( format.gendf.read.covariance.createCrossSectionCovarianceData                  format/gendf/read/covariance/createCrossSectionCovarianceData.test.cpp )
add_cpp_test( format.gendf.read.covariance.createCrossSectionCovarianceDataFromFile          format/gendf/read/covariance/createCrossSectionCovarianceDataFromFile.test.cpp )
add_cpp_test( format.gendf.read.covariance.createAngularDistributionCovarianceMatrix         format/gendf/read/covariance/createAngularDistributionCovarianceMatrix.test.cpp )
add_cpp_test( format.gendf.read.covariance.createAngularDistributionCovarianceData           format/gendf/read/covariance/createAngularDistributionCovarianceData.test.cpp )
add_cpp_test( format.gendf.read.covariance.createAngularDistributionCovarianceDataFromFile   format/gendf/read/covariance/createAngularDistributionCovarianceDataFromFile.test.cpp )
add_cpp_test( format.gendf.read.createMultiplicity                                           format/gendf/read/createMultiplicity.test.cpp )
add_cpp_test( format.gendf.read.createMultigroupCrossSection                                 format/gendf/read/createMultigroupCrossSection.test.cpp )
add_cpp_test( format.gendf.read.createMultigroupReactionProducts                             format/gendf/read/createMultigroupReactionProducts.test.cpp )
add_cpp_test( format.gendf.read.createMultigroupReaction                                     format/gendf/read/createMultigroupReaction.test.cpp )
add_cpp_test( format.gendf.read.createMultigroupReactions                                    format/gendf/read/createMultigroupReactions.test.cpp )
add_cpp_test( format.gendf.read.createMultigroupProjectileTarget                             format/gendf/read/createMultigroupProjectileTarget.test.cpp )
add_cpp_test( format.gendf.read.createMultigroupProjectileTargetFromFile                     format/gendf/read/createMultigroupProjectileTargetFromFile.test.cpp )

add_cpp_test( format.gnds.read.convertEnergy                                                 format/gnds/read/convertEnergy.test.cpp )
add_cpp_test( format.gnds.read.convertEnergies                                               format/gnds/read/convertEnergies.test.cpp )
add_cpp_test( format.gnds.read.convertCrossSection                                           format/gnds/read/convertCrossSection.test.cpp )
add_cpp_test( format.gnds.read.convertCrossSections                                          format/gnds/read/convertCrossSections.test.cpp )
add_cpp_test( format.gnds.read.convertInverseEnergy                                          format/gnds/read/convertInverseEnergy.test.cpp )
add_cpp_test( format.gnds.read.convertInverseEnergySquared                                   format/gnds/read/convertInverseEnergySquared.test.cpp )
add_cpp_test( format.gnds.read.convertSquareRootEnergy                                       format/gnds/read/convertSquareRootEnergy.test.cpp )
add_cpp_test( format.gnds.read.convertInverseEnergies                                        format/gnds/read/convertInverseEnergies.test.cpp )
add_cpp_test( format.gnds.read.convertInverseLengths                                         format/gnds/read/convertInverseLengths.test.cpp )
add_cpp_test( format.gnds.read.convertSquareRootEnergies                                     format/gnds/read/convertSquareRootEnergies.test.cpp )
add_cpp_test( format.gnds.read.convertMass                                                   format/gnds/read/convertMass.test.cpp )
add_cpp_test( format.gnds.read.convertVarianceScalingFactors                                 format/gnds/read/convertVarianceScalingFactors.test.cpp )
add_cpp_test( format.gnds.read.convertRadius                                                 format/gnds/read/convertRadius.test.cpp )
add_cpp_test( format.gnds.read.convertRadii                                                  format/gnds/read/convertRadii.test.cpp )
add_cpp_test( format.gnds.read.convertTemperature                                            format/gnds/read/convertTemperature.test.cpp )
add_cpp_test( format.gnds.read.convertTemperatures                                           format/gnds/read/convertTemperatures.test.cpp )
add_cpp_test( format.gnds.read.createInteractionType                                         format/gnds/read/createInteractionType.test.cpp )
add_cpp_test( format.gnds.read.createInterpolationType                                       format/gnds/read/createInterpolationType.test.cpp )
add_cpp_test( format.gnds.read.createReferenceFrame                                          format/gnds/read/createReferenceFrame.test.cpp )
add_cpp_test( format.gnds.read.createStorageOrder                                            format/gnds/read/createStorageOrder.test.cpp )
add_cpp_test( format.gnds.read.createParticleIdentifier                                      format/gnds/read/createParticleIdentifier.test.cpp )
add_cpp_test( format.gnds.read.readShape                                                     format/gnds/read/readShape.test.cpp )
add_cpp_test( format.gnds.read.resolveLink                                                   format/gnds/read/resolveLink.test.cpp )
add_cpp_test( format.gnds.read.readDouble                                                    format/gnds/read/readDouble.test.cpp )
add_cpp_test( format.gnds.read.readInteger                                                   format/gnds/read/readInteger.test.cpp )
add_cpp_test( format.gnds.read.readFraction                                                  format/gnds/read/readFraction.test.cpp )
add_cpp_test( format.gnds.read.readFractionFromString                                        format/gnds/read/readFractionFromString.test.cpp )
add_cpp_test( format.gnds.read.readString                                                    format/gnds/read/readString.test.cpp )
add_cpp_test( format.gnds.read.readAxis                                                      format/gnds/read/readAxis.test.cpp )
add_cpp_test( format.gnds.read.readGrid                                                      format/gnds/read/readGrid.test.cpp )
add_cpp_test( format.gnds.read.readAxes                                                      format/gnds/read/readAxes.test.cpp )
add_cpp_test( format.gnds.read.readValues                                                    format/gnds/read/readValues.test.cpp )
add_cpp_test( format.gnds.read.readConstant1d                                                format/gnds/read/readConstant1d.test.cpp )
add_cpp_test( format.gnds.read.readLegendre                                                  format/gnds/read/readLegendre.test.cpp )
add_cpp_test( format.gnds.read.readPolynomial1d                                              format/gnds/read/readPolynomial1d.test.cpp )
add_cpp_test( format.gnds.read.readXYs1d                                                     format/gnds/read/readXYs1d.test.cpp )
add_cpp_test( format.gnds.read.readArray                                                     format/gnds/read/readArray.test.cpp )
add_cpp_test( format.gnds.read.readColumn                                                    format/gnds/read/readColumn.test.cpp )
add_cpp_test( format.gnds.read.readColumnHeaders                                             format/gnds/read/readColumnHeaders.test.cpp )
add_cpp_test( format.gnds.read.readData                                                      format/gnds/read/readData.test.cpp )
add_cpp_test( format.gnds.read.readTable                                                     format/gnds/read/readTable.test.cpp )
add_cpp_test( format.gnds.read.createStyleLabel                                              format/gnds/read/createStyleLabel.test.cpp )
add_cpp_test( format.gnds.read.createDocumentation                                           format/gnds/read/createDocumentation.test.cpp )
add_cpp_test( format.gnds.read.pops.createMass                                               format/gnds/read/pops/createMass.test.cpp )
add_cpp_test( format.gnds.read.pops.createEnergy                                             format/gnds/read/pops/createEnergy.test.cpp )
add_cpp_test( format.gnds.read.pops.createSpin                                               format/gnds/read/pops/createSpin.test.cpp )
add_cpp_test( format.gnds.read.pops.createParity                                             format/gnds/read/pops/createParity.test.cpp )
add_cpp_test( format.gnds.read.pops.createParticle                                           format/gnds/read/pops/createParticle.test.cpp )
add_cpp_test( format.gnds.read.pops.createParticleDatabase                                   format/gnds/read/pops/createParticleDatabase.test.cpp )
add_cpp_test( format.gnds.read.resonances.createTabulatedRadius                              format/gnds/read/resonances/createTabulatedRadius.test.cpp )
add_cpp_test( format.gnds.read.resonances.createRadius                                       format/gnds/read/resonances/createRadius.test.cpp )
add_cpp_test( format.gnds.read.resonances.createParticles                                    format/gnds/read/resonances/createParticles.test.cpp )
add_cpp_test( format.gnds.read.resonances.rmatrix.createBoundaryCondition                    format/gnds/read/resonances/rmatrix/createBoundaryCondition.test.cpp )
add_cpp_test( format.gnds.read.resonances.rmatrix.createFormalism                            format/gnds/read/resonances/rmatrix/createFormalism.test.cpp )
add_cpp_test( format.gnds.read.resonances.rmatrix.createBackground                           format/gnds/read/resonances/rmatrix/createBackground.test.cpp )
add_cpp_test( format.gnds.read.resonances.rmatrix.createResonanceReaction                    format/gnds/read/resonances/rmatrix/createResonanceReaction.test.cpp )
add_cpp_test( format.gnds.read.resonances.rmatrix.createResonanceReactions                   format/gnds/read/resonances/rmatrix/createResonanceReactions.test.cpp )
add_cpp_test( format.gnds.read.resonances.rmatrix.createCompoundSystem                       format/gnds/read/resonances/rmatrix/createCompoundSystem.test.cpp )
add_cpp_test( format.gnds.read.thermal.createDebyeWallerIntegralData                         format/gnds/read/thermal/createDebyeWallerIntegralData.test.cpp )
add_cpp_test( format.gnds.read.thermal.createCoherentElasticScattering                       format/gnds/read/thermal/createCoherentElasticScattering.test.cpp )
add_cpp_test( format.gnds.read.thermal.createIncoherentElasticScattering                     format/gnds/read/thermal/createIncoherentElasticScattering.test.cpp )
add_cpp_test( format.gnds.read.readCovarianceMatrix                                          format/gnds/read/readCovarianceMatrix.test.cpp )
add_cpp_test( format.gnds.read.createPolynomialMultiplicity                                  format/gnds/read/createPolynomialMultiplicity.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedMultiplicity                                   format/gnds/read/createTabulatedMultiplicity.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedFormFactorFromNodes                            format/gnds/read/createTabulatedFormFactorFromNodes.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedScatteringFunctionFromNodes                    format/gnds/read/createTabulatedScatteringFunctionFromNodes.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedCrossSection                                   format/gnds/read/createTabulatedCrossSection.test.cpp )
add_cpp_test( format.gnds.read.createMultiplicity                                            format/gnds/read/createMultiplicity.test.cpp )
add_cpp_test( format.gnds.read.createQValue                                                  format/gnds/read/createQValue.test.cpp )
add_cpp_test( format.gnds.read.createCoherentDistributionData                                format/gnds/read/createCoherentDistributionData.test.cpp )
add_cpp_test( format.gnds.read.createIncoherentDistributionData                              format/gnds/read/createIncoherentDistributionData.test.cpp )
add_cpp_test( format.gnds.read.createUncorrelatedDistributionData                            format/gnds/read/createUncorrelatedDistributionData.test.cpp )
add_cpp_test( format.gnds.read.createTwoBodyDistributionData                                 format/gnds/read/createTwoBodyDistributionData.test.cpp )
add_cpp_test( format.gnds.read.createLegendreAngularDistributionFunction                     format/gnds/read/createLegendreAngularDistributionFunction.test.cpp )
add_cpp_test( format.gnds.read.createLegendreAngularDistributionFunctions                    format/gnds/read/createLegendreAngularDistributionFunctions.test.cpp )
add_cpp_test( format.gnds.read.createLegendreAngularDistributions                            format/gnds/read/createLegendreAngularDistributions.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedAngularDistributionFunction                    format/gnds/read/createTabulatedAngularDistributionFunction.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedAngularDistributionFunctions                   format/gnds/read/createTabulatedAngularDistributionFunctions.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedAngularDistributions                           format/gnds/read/createTabulatedAngularDistributions.test.cpp )
add_cpp_test( format.gnds.read.createMixedAngularDistributions                               format/gnds/read/createMixedAngularDistributions.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedEnergyDistributionFunction                     format/gnds/read/createTabulatedEnergyDistributionFunction.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedEnergyDistributionFunctions                    format/gnds/read/createTabulatedEnergyDistributionFunctions.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedEnergyDistributions                            format/gnds/read/createTabulatedEnergyDistributions.test.cpp )
add_cpp_test( format.gnds.read.createTabulatedAverageEnergy                                  format/gnds/read/createTabulatedAverageEnergy.test.cpp )
add_cpp_test( format.gnds.read.createReaction                                                format/gnds/read/createReaction.test.cpp )
add_cpp_test( format.gnds.read.createReactions                                               format/gnds/read/createReactions.test.cpp )
add_cpp_test( format.gnds.read.atomic.createElectronSubshellConfiguration                    format/gnds/read/atomic/createElectronSubshellConfiguration.test.cpp )
add_cpp_test( format.gnds.read.covariance.createScalingType                                  format/gnds/read/covariance/createScalingType.test.cpp )
add_cpp_test( format.gnds.read.covariance.createVarianceScaling                              format/gnds/read/covariance/createVarianceScaling.test.cpp )
add_cpp_test( format.gnds.read.covariance.createCrossSectionCovarianceMatrix                 format/gnds/read/covariance/createCrossSectionCovarianceMatrix.test.cpp )
add_cpp_test( format.gnds.read.covariance.createCovarianceData                               format/gnds/read/covariance/createCovarianceData.test.cpp )
add_cpp_test( format.gnds.read.createProjectileTarget                                        format/gnds/read/createProjectileTarget.test.cpp )
add_cpp_test( format.gnds.read.createProjectileTargetFromFile                                format/gnds/read/createProjectileTargetFromFile.test.cpp )
add_cpp_test( format.gnds.read.createAtomicRelaxation                                        format/gnds/read/createAtomicRelaxation.test.cpp )
add_cpp_test( format.gnds.read.createAtomicRelaxationFromFile                                format/gnds/read/createAtomicRelaxationFromFile.test.cpp )
add_cpp_test( format.gnds.read.createThermalScattering                                       format/gnds/read/createThermalScattering.test.cpp )
add_cpp_test( format.gnds.read.createThermalScatteringFromFile                               format/gnds/read/createThermalScatteringFromFile.test.cpp )

add_cpp_test( format.gnds.write.determineDepth                                               format/gnds/write/determineDepth.test.cpp )
add_cpp_test( format.gnds.write.createInteractionType                                        format/gnds/write/createInteractionType.test.cpp )
add_cpp_test( format.gnds.write.createInterpolationType                                      format/gnds/write/createInterpolationType.test.cpp )
add_cpp_test( format.gnds.write.toString                                                     format/gnds/write/toString.test.cpp )
add_cpp_test( format.gnds.write.insertDouble                                                 format/gnds/write/insertDouble.test.cpp )
add_cpp_test( format.gnds.write.insertInteger                                                format/gnds/write/insertInteger.test.cpp )
add_cpp_test( format.gnds.write.insertFraction                                               format/gnds/write/insertFraction.test.cpp )
add_cpp_test( format.gnds.write.insertString                                                 format/gnds/write/insertString.test.cpp )
add_cpp_test( format.gnds.write.insertParticle                                               format/gnds/write/insertParticle.test.cpp )
add_cpp_test( format.gnds.write.insertParticleDatabase                                       format/gnds/write/insertParticleDatabase.test.cpp )
add_cpp_test( format.gnds.write.insertAxis                                                   format/gnds/write/insertAxis.test.cpp )
add_cpp_test( format.gnds.write.insertAxes                                                   format/gnds/write/insertAxes.test.cpp )
add_cpp_test( format.gnds.write.insertValues                                                 format/gnds/write/insertValues.test.cpp )
add_cpp_test( format.gnds.write.insertConstant1d                                             format/gnds/write/insertConstant1d.test.cpp )
add_cpp_test( format.gnds.write.insertPolynomial1d                                           format/gnds/write/insertPolynomial1d.test.cpp )
add_cpp_test( format.gnds.write.insertXYs1d                                                  format/gnds/write/insertXYs1d.test.cpp )
add_cpp_test( format.gnds.write.insertTabulatedFunction                                      format/gnds/write/insertTabulatedFunction.test.cpp )
add_cpp_test( format.gnds.write.insertData                                                   format/gnds/write/insertData.test.cpp )
add_cpp_test( format.gnds.write.insertColumn                                                 format/gnds/write/insertColumn.test.cpp )
add_cpp_test( format.gnds.write.insertColumnHeaders                                          format/gnds/write/insertColumnHeaders.test.cpp )
add_cpp_test( format.gnds.write.insertTable                                                  format/gnds/write/insertTable.test.cpp )

add_cpp_test( format.gnds.write.resonances.insertScatteringRadius                            format/gnds/write/resonances/insertScatteringRadius.test.cpp )
add_cpp_test( format.gnds.write.resonances.insertHardSphereRadius                            format/gnds/write/resonances/insertHardSphereRadius.test.cpp )
add_cpp_test( format.gnds.write.resonances.rmatrix.createFormalism                           format/gnds/write/resonances/rmatrix/createFormalism.test.cpp )
add_cpp_test( format.gnds.write.resonances.rmatrix.createBoundaryCondition                   format/gnds/write/resonances/rmatrix/createBoundaryCondition.test.cpp )
add_cpp_test( format.gnds.write.resonances.rmatrix.insertResonanceParameters                 format/gnds/write/resonances/rmatrix/insertResonanceParameters.test.cpp )
add_cpp_test( format.gnds.write.resonances.rmatrix.insertResonanceReactions                  format/gnds/write/resonances/rmatrix/insertResonanceReactions.test.cpp )
add_cpp_test( format.gnds.write.resonances.rmatrix.insertExternalRMatrix                     format/gnds/write/resonances/rmatrix/insertExternalRMatrix.test.cpp )
add_cpp_test( format.gnds.write.resonances.rmatrix.insertChannels                            format/gnds/write/resonances/rmatrix/insertChannels.test.cpp )
add_cpp_test( format.gnds.write.resonances.rmatrix.insertSpinGroup                           format/gnds/write/resonances/rmatrix/insertSpinGroup.test.cpp )
add_cpp_test( format.gnds.write.resonances.rmatrix.insertRMatrix                             format/gnds/write/resonances/rmatrix/insertRMatrix.test.cpp )
add_cpp_test( format.gnds.write.insertTemperature                                            format/gnds/write/insertTemperature.test.cpp )
add_cpp_test( format.gnds.write.insertDocumentation                                          format/gnds/write/insertDocumentation.test.cpp )
add_cpp_test( format.gnds.write.insertCrossSection                                           format/gnds/write/insertCrossSection.test.cpp )
add_cpp_test( format.gnds.write.insertBackgroundCrossSection                                 format/gnds/write/insertBackgroundCrossSection.test.cpp )
add_cpp_test( format.gnds.write.insertMultiplicity                                           format/gnds/write/insertMultiplicity.test.cpp )
add_cpp_test( format.gnds.write.insertQ                                                      format/gnds/write/insertQ.test.cpp )
add_cpp_test( format.gnds.write.insertOutputChannel                                          format/gnds/write/insertOutputChannel.test.cpp )
add_cpp_test( format.gnds.write.insertReactions                                              format/gnds/write/insertReactions.test.cpp )
add_cpp_test( format.gnds.write.insertCrossSectionSums                                       format/gnds/write/insertCrossSectionSums.test.cpp )
add_cpp_test( format.gnds.write.insertSums                                                   format/gnds/write/insertSums.test.cpp )

add_cpp_test( dryad.external.ComptonProfiles                                                 dryad/external/ComptonProfiles.test.cpp )
add_cpp_test( dryad.external.KleinNishina                                                    dryad/external/KleinNishina.test.cpp )
add_cpp_test( dryad.external.ripl3.LevelEntry                                                dryad/external/ripl3/LevelEntry.test.cpp )
add_cpp_test( dryad.external.ripl3.Levels                                                    dryad/external/ripl3/Levels.test.cpp )
add_cpp_test( dryad.external.ame.MassEntry                                                   dryad/external/ame/MassEntry.test.cpp )
add_cpp_test( dryad.external.ame.Masses                                                      dryad/external/ame/Masses.test.cpp )

# psychic tests

add_cpp_test( psychic.TestStatus                                                             psychic/TestStatus.test.cpp )
add_cpp_test( psychic.covariance.PositiveSemiDefinite                                        psychic/covariance/PositiveSemiDefinite.test.cpp )
add_cpp_test( psychic.covariance.PositiveVariances                                           psychic/covariance/PositiveVariances.test.cpp )
add_cpp_test( psychic.covariance.EigenvalueRatio                                             psychic/covariance/EigenvalueRatio.test.cpp )
add_cpp_test( psychic.covariance.BoundedCorrelations                                         psychic/covariance/BoundedCorrelations.test.cpp )
add_cpp_test( psychic.covariance.DiagonalCorrelations                                        psychic/covariance/DiagonalCorrelations.test.cpp )
add_cpp_test( psychic.covariance.TestSuite                                                   psychic/covariance/TestSuite.test.cpp )

# reconr tests

add_cpp_test( reconr.unioniseCrossSections                                                   reconr/unioniseCrossSections.test.cpp )
add_cpp_test( reconr.calculateSummationCrossSections                                         reconr/calculateSummationCrossSections.test.cpp )

# medic tests

add_cpp_test( medic.pruneCrossSection                                                        medic/pruneCrossSection.test.cpp )
add_cpp_test( medic.pruneCrossSections                                                       medic/pruneCrossSections.test.cpp )
add_cpp_test( medic.curateComptonProfiles                                                    medic/curateComptonProfiles.test.cpp )
add_cpp_test( medic.covariance.pruneSmallEigenvalues                                         medic/covariance/pruneSmallEigenvalues.test.cpp )

# acer tests

add_cpp_test( acer.processElectronPhotonRelaxation                                           acer/processElectronPhotonRelaxation.test.cpp )
