#######################################################################
# Setup
#######################################################################

enable_testing()

FetchContent_MakeAvailable( Catch2 )

function( add_cpp_test name source )

  set( test_name "dryad.${name}.test" )
  add_executable( ${test_name} ${source} )
  add_test( NAME ${test_name} COMMAND ${test_name} )
  target_link_libraries( ${test_name} PRIVATE dryad )
  target_link_libraries( ${test_name} PRIVATE Catch2::Catch2WithMain )

  file( GLOB resources "resources/*" )
  foreach( resource ${resources} )
    file( COPY "${resource}" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}" )
  endforeach()

endfunction()

#######################################################################
# Unit testing directories
#######################################################################

message( STATUS "Adding dryad C++ unit testing" )

add_cpp_test( base.UniformDistribution                                   base/UniformDistribution.test.cpp )

add_cpp_test( atomic.ElectronSubshellConfiguration                       atomic/ElectronSubshellConfiguration.test.cpp )
add_cpp_test( atomic.NonRadiativeTransitionData                          atomic/NonRadiativeTransitionData.test.cpp )
add_cpp_test( atomic.RadiativeTransitionData                             atomic/RadiativeTransitionData.test.cpp )

add_cpp_test( covariance.matrix                                          covariance/matrix.test.cpp )
add_cpp_test( covariance.CovarianceBlock                                 covariance/CovarianceBlock.test.cpp )
add_cpp_test( covariance.CrossSectionCovarianceBlock                     covariance/CrossSectionCovarianceBlock.test.cpp )
add_cpp_test( covariance.CrossSectionMetadata                            covariance/CrossSectionMetadata.test.cpp )
add_cpp_test( covariance.LinearCombinationCovariance                     covariance/LinearCombinationCovariance.test.cpp )
add_cpp_test( covariance.VarianceScaling                                 covariance/VarianceScaling.test.cpp )

add_cpp_test( id.ElectronSubshellID                                      id/ElectronSubshellID.test.cpp )
add_cpp_test( id.ElementID                                               id/ElementID.test.cpp )
add_cpp_test( id.LevelID                                                 id/LevelID.test.cpp )
add_cpp_test( id.ParticleID                                              id/ParticleID.test.cpp )
add_cpp_test( id.ReactionType                                            id/ReactionType.test.cpp )

add_cpp_test( Documentation                                              Documentation.test.cpp )

add_cpp_test( CoherentDistributionData                                   CoherentDistributionData.test.cpp )
add_cpp_test( IncoherentDistributionData                                 IncoherentDistributionData.test.cpp )

add_cpp_test( TabulatedFormFactor                                        TabulatedFormFactor.test.cpp )
add_cpp_test( TabulatedScatteringFunction                                TabulatedScatteringFunction.test.cpp )
add_cpp_test( PolynomialMultiplicity                                     PolynomialMultiplicity.test.cpp )
add_cpp_test( TabulatedMultiplicity                                      TabulatedMultiplicity.test.cpp )
add_cpp_test( TabulatedAverageCosine                                     TabulatedAverageCosine.test.cpp )
add_cpp_test( TabulatedAverageEnergy                                     TabulatedAverageEnergy.test.cpp )
add_cpp_test( LegendreAngularDistributionFunction                        LegendreAngularDistributionFunction.test.cpp )
add_cpp_test( LegendreAngularDistribution                                LegendreAngularDistribution.test.cpp )
add_cpp_test( LegendreAngularDistributions                               LegendreAngularDistributions.test.cpp )
add_cpp_test( TabulatedAngularDistributionFunction                       TabulatedAngularDistributionFunction.test.cpp )
add_cpp_test( TabulatedAngularDistribution                               TabulatedAngularDistribution.test.cpp )
add_cpp_test( TabulatedAngularDistributions                              TabulatedAngularDistributions.test.cpp )
add_cpp_test( UniformAngularDistribution                                 UniformAngularDistribution.test.cpp )
add_cpp_test( UniformAngularDistributions                                UniformAngularDistributions.test.cpp )
add_cpp_test( UniformEnergyDistribution                                  UniformEnergyDistribution.test.cpp )
add_cpp_test( UniformEnergyDistributions                                 UniformEnergyDistributions.test.cpp )
add_cpp_test( TabulatedEnergyDistributionFunction                        TabulatedEnergyDistributionFunction.test.cpp )
add_cpp_test( TabulatedEnergyDistribution                                TabulatedEnergyDistribution.test.cpp )
add_cpp_test( TabulatedEnergyDistributions                               TabulatedEnergyDistributions.test.cpp )
add_cpp_test( TwoBodyDistributionData                                    TwoBodyDistributionData.test.cpp )
add_cpp_test( UncorrelatedDistributionData                               UncorrelatedDistributionData.test.cpp )
add_cpp_test( ReactionProduct                                            ReactionProduct.test.cpp )
add_cpp_test( TabulatedCrossSection                                      TabulatedCrossSection.test.cpp )
add_cpp_test( Reaction                                                   Reaction.test.cpp )
add_cpp_test( ProjectileTarget                                           ProjectileTarget.test.cpp )
add_cpp_test( AtomicRelaxation                                           AtomicRelaxation.test.cpp )

add_cpp_test( format.createIndex                                         format/createIndex.test.cpp )
add_cpp_test( format.createVector                                        format/createVector.test.cpp )

add_cpp_test( format.ace.createTabulatedScatteringFunction               format/ace/createTabulatedScatteringFunction.test.cpp )
add_cpp_test( format.ace.createTabulatedAngularDistributionFunction      format/ace/createTabulatedAngularDistributionFunction.test.cpp )
add_cpp_test( format.ace.createTabulatedEnergyDistributionFunction       format/ace/createTabulatedEnergyDistributionFunction.test.cpp )
add_cpp_test( format.ace.electroatomic.createPdfFromCdf                  format/ace/electroatomic/createPdfFromCdf.test.cpp )
add_cpp_test( format.ace.electroatomic.createReactionNumbers             format/ace/electroatomic/createReactionNumbers.test.cpp )
add_cpp_test( format.ace.electroatomic.createPartialReactionNumbers      format/ace/electroatomic/createPartialReactionNumbers.test.cpp )
add_cpp_test( format.ace.electroatomic.createTabulatedCrossSections      format/ace/electroatomic/createTabulatedCrossSections.test.cpp )
add_cpp_test( format.ace.electroatomic.createReactions                   format/ace/electroatomic/createReactions.test.cpp )
add_cpp_test( format.ace.electroatomic.createProjectileTarget            format/ace/electroatomic/createProjectileTarget.test.cpp )
add_cpp_test( format.ace.photoatomic.createReactionNumbers               format/ace/photoatomic/createReactionNumbers.test.cpp )
add_cpp_test( format.ace.photoatomic.createPartialReactionNumbers        format/ace/photoatomic/createPartialReactionNumbers.test.cpp )
add_cpp_test( format.ace.photoatomic.createTabulatedCrossSections        format/ace/photoatomic/createTabulatedCrossSections.test.cpp )
add_cpp_test( format.ace.photoatomic.createReactionProducts              format/ace/photoatomic/createReactionProducts.test.cpp )
add_cpp_test( format.ace.photoatomic.createReactions                     format/ace/photoatomic/createReactions.test.cpp )
add_cpp_test( format.ace.photoatomic.createProjectileTarget              format/ace/photoatomic/createProjectileTarget.test.cpp )
add_cpp_test( format.ace.createProjectileTargetFromFile                  format/ace/createProjectileTargetFromFile.test.cpp )

add_cpp_test( format.endf.ReactionInformation                            format/endf/ReactionInformation.test.cpp )
add_cpp_test( format.endf.createBoundaries                               format/endf/createBoundaries.test.cpp )
add_cpp_test( format.endf.createInterpolant                              format/endf/createInterpolant.test.cpp )
add_cpp_test( format.endf.createInterpolants                             format/endf/createInterpolants.test.cpp )
add_cpp_test( format.endf.createProjectileIdentifier                     format/endf/createProjectileIdentifier.test.cpp )
add_cpp_test( format.endf.createProductIdentifier                        format/endf/createProductIdentifier.test.cpp )
add_cpp_test( format.endf.createTargetIdentifier                         format/endf/createTargetIdentifier.test.cpp )
add_cpp_test( format.endf.createInteractionType                          format/endf/createInteractionType.test.cpp )
add_cpp_test( format.endf.atomic.createElectronSubshellID                format/endf/atomic/createElectronSubshellID.test.cpp )
add_cpp_test( format.endf.atomic.createElectronSubshellConfiguration     format/endf/atomic/createElectronSubshellConfiguration.test.cpp )
add_cpp_test( format.endf.covariance.createMatrix                        format/endf/covariance/createMatrix.test.cpp )
add_cpp_test( format.endf.covariance.createVarianceScaling               format/endf/covariance/createVarianceScaling.test.cpp )
add_cpp_test( format.endf.covariance.createCrossSectionCovarianceBlock   format/endf/covariance/createCrossSectionCovarianceBlock.test.cpp )
add_cpp_test( format.endf.createTabulatedCrossSection                    format/endf/createTabulatedCrossSection.test.cpp )
add_cpp_test( format.endf.createPolynomialMultiplicity                   format/endf/createPolynomialMultiplicity.test.cpp )
add_cpp_test( format.endf.createTabulatedMultiplicity                    format/endf/createTabulatedMultiplicity.test.cpp )
add_cpp_test( format.endf.createMultiplicity                             format/endf/createMultiplicity.test.cpp )
add_cpp_test( format.endf.createLegendreAngularDistribution              format/endf/createLegendreAngularDistribution.test.cpp )
add_cpp_test( format.endf.createLegendreAngularDistributions             format/endf/createLegendreAngularDistributions.test.cpp )
add_cpp_test( format.endf.createTabulatedAngularDistribution             format/endf/createTabulatedAngularDistribution.test.cpp )
add_cpp_test( format.endf.createTabulatedAngularDistributions            format/endf/createTabulatedAngularDistributions.test.cpp )
add_cpp_test( format.endf.createTabulatedEnergyDistribution              format/endf/createTabulatedEnergyDistribution.test.cpp )
add_cpp_test( format.endf.createTabulatedEnergyDistributions             format/endf/createTabulatedEnergyDistributions.test.cpp )
add_cpp_test( format.endf.createTabulatedAverageEnergy                   format/endf/createTabulatedAverageEnergy.test.cpp )
add_cpp_test( format.endf.createTabulatedFormFactor                      format/endf/createTabulatedFormFactor.test.cpp )
add_cpp_test( format.endf.createTabulatedScatteringFunction              format/endf/createTabulatedScatteringFunction.test.cpp )
add_cpp_test( format.endf.createReactionProduct                          format/endf/createReactionProduct.test.cpp )
add_cpp_test( format.endf.createReactionProducts                         format/endf/createReactionProducts.test.cpp )
add_cpp_test( format.endf.createReaction                                 format/endf/createReaction.test.cpp )
add_cpp_test( format.endf.createReactions                                format/endf/createReactions.test.cpp )
add_cpp_test( format.endf.createDocumentation                            format/endf/createDocumentation.test.cpp )
add_cpp_test( format.endf.createProjectileTarget                         format/endf/createProjectileTarget.test.cpp )
add_cpp_test( format.endf.createProjectileTargetFromFile                 format/endf/createProjectileTargetFromFile.test.cpp )
add_cpp_test( format.endf.createAtomicRelaxation                         format/endf/createAtomicRelaxation.test.cpp )
add_cpp_test( format.endf.createAtomicRelaxationFromFile                 format/endf/createAtomicRelaxationFromFile.test.cpp )

add_cpp_test( format.endf.createEndfIndex                                format/endf/createEndfIndex.test.cpp )
add_cpp_test( format.endf.createEndfBoundaries                           format/endf/createEndfBoundaries.test.cpp )
add_cpp_test( format.endf.createEndfInterpolant                          format/endf/createEndfInterpolant.test.cpp )
add_cpp_test( format.endf.createEndfInterpolants                         format/endf/createEndfInterpolants.test.cpp )
add_cpp_test( format.endf.createEndfSubLibraryType                       format/endf/createEndfSubLibraryType.test.cpp )
add_cpp_test( format.endf.atomic.createEndfSubshellDesignator            format/endf/atomic/createEndfSubshellDesignator.test.cpp )
add_cpp_test( format.endf.atomic.createEndfSubshellData                  format/endf/atomic/createEndfSubshellData.test.cpp )
add_cpp_test( format.endf.createEndfFile3Section.                        format/endf/createEndfFile3Section.test.cpp )
add_cpp_test( format.endf.createAtomicRelaxationEndfFile                 format/endf/createAtomicRelaxationEndfFile.test.cpp )

add_cpp_test( format.gnds.convertEnergy                                  format/gnds/convertEnergy.test.cpp )
add_cpp_test( format.gnds.convertCrossSections                           format/gnds/convertCrossSections.test.cpp )
add_cpp_test( format.gnds.convertEnergies                                format/gnds/convertEnergies.test.cpp )
add_cpp_test( format.gnds.convertInverseLengths                          format/gnds/convertInverseLengths.test.cpp )
add_cpp_test( format.gnds.createInteractionType                          format/gnds/createInteractionType.test.cpp )
add_cpp_test( format.gnds.createInterpolationType                        format/gnds/createInterpolationType.test.cpp )
add_cpp_test( format.gnds.createReferenceFrame                           format/gnds/createReferenceFrame.test.cpp )
add_cpp_test( format.gnds.createParticleIdentifier                       format/gnds/createParticleIdentifier.test.cpp )
add_cpp_test( format.gnds.readShape                                      format/gnds/readShape.test.cpp )
add_cpp_test( format.gnds.resolveLink                                    format/gnds/resolveLink.test.cpp )
add_cpp_test( format.gnds.readAxis                                       format/gnds/readAxis.test.cpp )
add_cpp_test( format.gnds.readGrid                                       format/gnds/readGrid.test.cpp )
add_cpp_test( format.gnds.readAxes                                       format/gnds/readAxes.test.cpp )
add_cpp_test( format.gnds.readValues                                     format/gnds/readValues.test.cpp )
add_cpp_test( format.gnds.readConstant1d                                 format/gnds/readConstant1d.test.cpp )
add_cpp_test( format.gnds.readLegendre                                   format/gnds/readLegendre.test.cpp )
add_cpp_test( format.gnds.readPolynomial1d                               format/gnds/readPolynomial1d.test.cpp )
add_cpp_test( format.gnds.readXYs1d                                      format/gnds/readXYs1d.test.cpp )
add_cpp_test( format.gnds.readArray                                      format/gnds/readArray.test.cpp )
add_cpp_test( format.gnds.readCovarianceMatrix                           format/gnds/readCovarianceMatrix.test.cpp )
add_cpp_test( format.gnds.createPolynomialMultiplicity                   format/gnds/createPolynomialMultiplicity.test.cpp )
add_cpp_test( format.gnds.createTabulatedMultiplicity                    format/gnds/createTabulatedMultiplicity.test.cpp )
add_cpp_test( format.gnds.createTabulatedFormFactorFromNodes             format/gnds/createTabulatedFormFactorFromNodes.test.cpp )
add_cpp_test( format.gnds.createTabulatedScatteringFunctionFromNodes     format/gnds/createTabulatedScatteringFunctionFromNodes.test.cpp )
add_cpp_test( format.gnds.createTabulatedCrossSection                    format/gnds/createTabulatedCrossSection.test.cpp )
add_cpp_test( format.gnds.createMultiplicity                             format/gnds/createMultiplicity.test.cpp )
add_cpp_test( format.gnds.createQValue                                   format/gnds/createQValue.test.cpp )
add_cpp_test( format.gnds.createLegendreAngularDistribution              format/gnds/createLegendreAngularDistribution.test.cpp )
add_cpp_test( format.gnds.createTabulatedAverageEnergy                   format/gnds/createTabulatedAverageEnergy.test.cpp )
add_cpp_test( format.gnds.createReaction                                 format/gnds/createReaction.test.cpp )
add_cpp_test( format.gnds.createReactions                                format/gnds/createReactions.test.cpp )
add_cpp_test( format.gnds.atomic.createElectronSubshellConfiguration     format/gnds/atomic/createElectronSubshellConfiguration.test.cpp )
add_cpp_test( format.gnds.covariance.createScalingType                   format/gnds/covariance/createScalingType.test.cpp )
add_cpp_test( format.gnds.covariance.createVarianceScaling               format/gnds/covariance/createVarianceScaling.test.cpp )
add_cpp_test( format.gnds.covariance.createCrossSectionCovarianceBlock   format/gnds/covariance/createCrossSectionCovarianceBlock.test.cpp )
add_cpp_test( format.gnds.createProjectileTarget                         format/gnds/createProjectileTarget.test.cpp )
add_cpp_test( format.gnds.createProjectileTargetFromFile                 format/gnds/createProjectileTargetFromFile.test.cpp )
add_cpp_test( format.gnds.createAtomicRelaxation                         format/gnds/createAtomicRelaxation.test.cpp )
add_cpp_test( format.gnds.createAtomicRelaxationFromFile                 format/gnds/createAtomicRelaxationFromFile.test.cpp )
