// include Catch2
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
using Catch::Matchers::WithinRel;

// what we are testing
#include "njoy/dryad/thermal/IncoherentElasticAngularCdf.hpp"

// other includes

// include files for generating test results
// #include "njoy/dryad/thermal/IncoherentElasticAngularPdf.hpp"
// #include "scion/integration/AdaptiveGaussLobatto.hpp"
// #include <iostream>
// #include <iomanip>

// convenience typedefs
using namespace njoy::dryad;

void verifyChunk( const thermal::IncoherentElasticAngularCdf& );

SCENARIO( "IncoherentElasticAngularCdf" ) {

  GIVEN( "valid incoherent scattering data" ) {

    WHEN( "the data is given explicitly" ) {

      double incident = 1.;
      double debyeWaller = 2.013538;

      thermal::IncoherentElasticAngularCdf chunk( incident, debyeWaller );

      THEN( "IncoherentElasticAngularCdf can be constructed and members can be tested" ) {

        verifyChunk( chunk );
      } // THEN
    } // WHEN
  } // GIVEN

  GIVEN( "comparison operators" ) {

    WHEN( "two instances of IncoherentElasticAngularCdf are given" ) {

      thermal::IncoherentElasticAngularCdf left( 1., 2.013538 );
      thermal::IncoherentElasticAngularCdf equal( 1., 2.013538 );
      thermal::IncoherentElasticAngularCdf different( 1e-5, 3. );

      THEN( "they can be compared" ) {

        CHECK( true == ( left == left ) );
        CHECK( true == ( left == equal ) );
        CHECK( false == ( left == different ) );

        CHECK( false == ( left != left ) );
        CHECK( false == ( left != equal ) );
        CHECK( true == ( left != different ) );
      } // THEN
    } // WHEN
  } // GIVEN
} // SCENARIO

void verifyChunk( const thermal::IncoherentElasticAngularCdf& chunk ) {

  CHECK_THAT( -1., WithinRel( chunk.lowerCosineLimit() ) );
  CHECK_THAT(  1., WithinRel( chunk.upperCosineLimit() ) );
  CHECK_THAT( 1., WithinRel( chunk.incidentEnergy() ) );
  CHECK_THAT( 2.013538, WithinRel( chunk.debyeWallerIntegral() ) );

  // verifying test results for the cdf by integrating the pdf
  // thermal::IncoherentElasticAngularPdf pdf( 1., 2.013538 );
  // njoy::scion::integration::AdaptiveGaussLobatto< double, double > integrator;
  // std::cout << std::setprecision( 15 ) << integrator( pdf, -1, -1, 1e-12 ) << std::endl;
  // std::cout << std::setprecision( 15 ) << integrator( pdf, -1, -0.5, 1e-12 ) << std::endl;
  // std::cout << std::setprecision( 15 ) << integrator( pdf, -1,  0, 1e-12 ) << std::endl;
  // std::cout << std::setprecision( 15 ) << integrator( pdf, -1,  0.5, 1e-12 ) << std::endl;
  // std::cout << std::setprecision( 15 ) << integrator( pdf, -1,  1, 1e-12 ) << std::endl;

  CHECK_THAT( 0.                   , WithinRel( chunk( -1.0 ) ) );
  CHECK_THAT( 0.00206297289828974  , WithinRel( chunk( -0.5 ), 5e-12 ) );
  CHECK_THAT( 0.017514164040693    , WithinRel( chunk(  0.  ), 5e-12 ) );
  CHECK_THAT( 0.133240021571662    , WithinRel( chunk(  0.5 ), 5e-12 ) );
  CHECK_THAT( 1.                   , WithinRel( chunk(  1.0 ) ) );

  // the lineariser has been tested a lot, results were generated by the test

  auto linear = chunk.linearise();
  CHECK( 147 == linear.numberPoints() );
  CHECK( 1 == linear.numberRegions() );
  CHECK( 147 == linear.cosines().size() );
  CHECK( 147 == linear.values().size() );
  CHECK( 1 == linear.boundaries().size() );
  CHECK( 1 == linear.interpolants().size() );
  CHECK( 146 == linear.boundaries()[0] );
  CHECK( InterpolationType::LinearLinear == linear.interpolants()[0] );
  CHECK_THAT( -1.  , WithinRel( linear.cosines().front() ) );
  CHECK_THAT(  1.  , WithinRel( linear.cosines().back() ) );
  CHECK_THAT( 0., WithinRel( linear.values().front() ) );
  CHECK_THAT( 1., WithinRel( linear.values().back() ) );
  CHECK( true == linear.isLinearised() );
}
