// include Catch2
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
using Catch::Matchers::WithinRel;

// what we are testing
#include "njoy/dryad/thermal/IncoherentElasticAngularDistribution.hpp"

// other includes

// convenience typedefs
using namespace njoy::dryad;

void verifyChunk( const thermal::IncoherentElasticAngularDistribution& );

SCENARIO( "IncoherentElasticAngularDistribution" ) {

  GIVEN( "valid incoherent scattering data" ) {

    WHEN( "the data is given explicitly" ) {

      double incident = 1.;
      double debyeWaller = 2.013538;

      thermal::IncoherentElasticAngularDistribution chunk( incident, debyeWaller );

      THEN( "IncoherentElasticAngularDistribution can be constructed and members can be tested" ) {

        verifyChunk( chunk );
      } // THEN
    } // WHEN
  } // GIVEN

  GIVEN( "comparison operators" ) {

    WHEN( "two instances of IncoherentElasticAngularDistribution are given" ) {

      thermal::IncoherentElasticAngularDistribution left( 1., 2.013538 );
      thermal::IncoherentElasticAngularDistribution equal( 1., 2.013538 );
      thermal::IncoherentElasticAngularDistribution different( 1e-5, 3. );

      THEN( "they can be compared" ) {

        CHECK( true == ( left == left ) );
        CHECK( true == ( left == equal ) );
        CHECK( false == ( left == different ) );

        CHECK( false == ( left != left ) );
        CHECK( false == ( left != equal ) );
        CHECK( true == ( left != different ) );
      } // THEN
    } // WHEN
  } // GIVEN
} // SCENARIO

void verifyChunk( const thermal::IncoherentElasticAngularDistribution& chunk ) {

  CHECK_THAT( 1., WithinRel( chunk.incidentEnergy() ) );
  CHECK_THAT( 2.013538, WithinRel( chunk.debyeWallerIntegral() ) );
  CHECK_THAT( 0.752316633727453, WithinRel( chunk.averageCosine(), 5e-12 ) );

  CHECK_THAT( -1., WithinRel( chunk.pdf().lowerCosineLimit() ) );
  CHECK_THAT(  1., WithinRel( chunk.pdf().upperCosineLimit() ) );
  CHECK_THAT( 1., WithinRel( chunk.pdf().incidentEnergy() ) );
  CHECK_THAT( 2.013538, WithinRel( chunk.pdf().debyeWallerIntegral() ) );

  // verifying test results for the integral and mean
  // njoy::scion::integration::AdaptiveGaussLobatto< double, double > integrator;
  // std::cout << std::setprecision( 15 ) << integrator( chunk, -1, 1, 1e-12 ) << std::endl;
  // auto mean = [&] ( double cosine ) { return cosine * chunk( cosine ); };
  // std::cout << std::setprecision( 15 ) << integrator( mean, -1, 1, 1e-12 ) << std::endl;

  CHECK_THAT( 1., WithinRel( chunk.pdf().integral() ) );
  CHECK_THAT( 0.752316633727453, WithinRel( chunk.pdf().mean(), 5e-12 ) );

  CHECK_THAT( -1., WithinRel( chunk.cdf().lowerCosineLimit() ) );
  CHECK_THAT(  1., WithinRel( chunk.cdf().upperCosineLimit() ) );
  CHECK_THAT( 1., WithinRel( chunk.cdf().incidentEnergy() ) );
  CHECK_THAT( 2.013538, WithinRel( chunk.cdf().debyeWallerIntegral() ) );

  // function evaluation

  CHECK_THAT( 1.280130036188690E-03, WithinRel( chunk( -1.0 ) ) );
  CHECK_THAT( 9.587878683533260E-03, WithinRel( chunk( -0.5 ) ) );
  CHECK_THAT( 7.181099970425270E-02, WithinRel( chunk(  0.  ) ) );
  CHECK_THAT( 5.378478231457790E-01, WithinRel( chunk(  0.5 ) ) );
  CHECK_THAT( 4.028356130036190E+00, WithinRel( chunk(  1.0 ) ) );

  // the lineariser has been tested a lot, results were generated by the test

  auto linear = chunk.linearise();
  CHECK( 129 == linear.pdf().numberPoints() );
  CHECK( 1 == linear.pdf().numberRegions() );
  CHECK( 129 == linear.pdf().cosines().size() );
  CHECK( 129 == linear.pdf().values().size() );
  CHECK( 1 == linear.pdf().boundaries().size() );
  CHECK( 1 == linear.pdf().interpolants().size() );
  CHECK( 128 == linear.pdf().boundaries()[0] );
  CHECK( InterpolationType::LinearLinear == linear.pdf().interpolants()[0] );
  CHECK_THAT( -1. , WithinRel( linear.pdf().cosines().front() ) );
  CHECK_THAT(  1. , WithinRel( linear.pdf().cosines().back() ) );
  CHECK_THAT( 1.280130036188690E-03, WithinRel( linear.pdf().values().front() ) );
  CHECK_THAT( 4.028356130036190E+00, WithinRel( linear.pdf().values().back() ) );
  CHECK( true == linear.pdf().isLinearised() );

  // not checking the cdf
}
