// include Catch2
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
using Catch::Matchers::WithinRel;

// what we are testing
#include "njoy/dryad/thermal/IncoherentElasticCrossSection.hpp"

// other includes

// convenience typedefs
using namespace njoy::dryad;

void verifyChunk( const thermal::IncoherentElasticCrossSection& );

SCENARIO( "IncoherentElasticCrossSection" ) {

  GIVEN( "valid incoherent scattering data" ) {

    WHEN( "the data is given explicitly" ) {

      double lower = 1e-5;
      double upper = 10.;
      double xs = 6.337872;
      double debyeWaller = 2.013538;

      thermal::IncoherentElasticCrossSection chunk( lower, upper, xs, debyeWaller );

      THEN( "IncoherentElasticCrossSection can be constructed and members can be tested" ) {

        verifyChunk( chunk );
      } // THEN
    } // WHEN
  } // GIVEN

  GIVEN( "comparison operators" ) {

    WHEN( "two instances of IncoherentElasticCrossSection are given" ) {

      thermal::IncoherentElasticCrossSection left( 1e-5, 10., 6.337872, 2.013538 );
      thermal::IncoherentElasticCrossSection equal( 1e-5, 10., 6.337872, 2.013538 );
      thermal::IncoherentElasticCrossSection different( 1e-5, 5., 7., 3. );

      THEN( "they can be compared" ) {

        CHECK( true == ( left == left ) );
        CHECK( true == ( left == equal ) );
        CHECK( false == ( left == different ) );

        CHECK( false == ( left != left ) );
        CHECK( false == ( left != equal ) );
        CHECK( true == ( left != different ) );
      } // THEN
    } // WHEN
  } // GIVEN
} // SCENARIO

void verifyChunk( const thermal::IncoherentElasticCrossSection& chunk ) {

  CHECK_THAT( 1e-5, WithinRel( chunk.lowerEnergyLimit() ) );
  CHECK_THAT( 10. , WithinRel( chunk.upperEnergyLimit() ) );
  CHECK_THAT( 6.337872, WithinRel( chunk.boundCrossSection() ) );
  CHECK_THAT( 2.013538, WithinRel( chunk.debyeWallerIntegral() ) );

  // results were compared with NJOY2016 using the actual energy values used by NJOY2016
  // the formula is implemented correctly but the results here were recalculated in excel

  CHECK_THAT( 6.337616775925780E+00, WithinRel( chunk( 1e-5 ) ) );
  CHECK_THAT( 6.335320375862280E+00, WithinRel( chunk( 1e-4 ) ) );
  CHECK_THAT( 6.312417292315570E+00, WithinRel( chunk( 1e-3 ) ) );
  CHECK_THAT( 6.089357527359890E+00, WithinRel( chunk( 1e-2 ) ) );
  CHECK_THAT( 4.352366592338050E+00, WithinRel( chunk( 1e-1 ) ) );
  CHECK_THAT( 7.866573603986530E-01, WithinRel( chunk( 1. ) ) );
  CHECK_THAT( 7.869074236493180E-02, WithinRel( chunk( 10. ) ) );

  // the lineariser has been tested a lot, results were generated by the test

  auto linear = chunk.linearise();
  CHECK( 97 == linear.numberPoints() );
  CHECK( 1 == linear.numberRegions() );
  CHECK( 97 == linear.energies().size() );
  CHECK( 97 == linear.values().size() );
  CHECK( 1 == linear.boundaries().size() );
  CHECK( 1 == linear.interpolants().size() );
  CHECK( 96 == linear.boundaries()[0] );
  CHECK( InterpolationType::LinearLinear == linear.interpolants()[0] );
  CHECK_THAT( 1e-5 , WithinRel( linear.energies().front() ) );
  CHECK_THAT( 10.  , WithinRel( linear.energies().back() ) );
  CHECK_THAT( 6.337616775925780E+00, WithinRel( linear.values().front() ) );
  CHECK_THAT( 7.869074236493180E-02, WithinRel( linear.values().back() ) );
  CHECK( true == linear.isLinearised() );
}
