// include Catch2
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>
using Catch::Matchers::WithinRel;

// what we are testing
#include "njoy/dryad/thermal/IncoherentElasticAngularPdf.hpp"

// other includes

// include files for generating test results
// #include "scion/integration/AdaptiveGaussLobatto.hpp"
// #include <iostream>
// #include <iomanip>

// convenience typedefs
using namespace njoy::dryad;

void verifyChunk( const thermal::IncoherentElasticAngularPdf& );

SCENARIO( "IncoherentElasticAngularPdf" ) {

  GIVEN( "valid incoherent scattering data" ) {

    WHEN( "the data is given explicitly" ) {

      double incident = 1.;
      double debyeWaller = 2.013538;

      thermal::IncoherentElasticAngularPdf chunk( incident, debyeWaller );

      THEN( "IncoherentElasticAngularPdf can be constructed and members can be tested" ) {

        verifyChunk( chunk );
      } // THEN

      THEN( "normalise does not do anything" ) {

        chunk.normalise();
        verifyChunk( chunk );
      } // THEN
    } // WHEN
  } // GIVEN

  GIVEN( "comparison operators" ) {

    WHEN( "two instances of IncoherentElasticAngularPdf are given" ) {

      thermal::IncoherentElasticAngularPdf left( 1., 2.013538 );
      thermal::IncoherentElasticAngularPdf equal( 1., 2.013538 );
      thermal::IncoherentElasticAngularPdf different( 1e-5, 3. );

      THEN( "they can be compared" ) {

        CHECK( true == ( left == left ) );
        CHECK( true == ( left == equal ) );
        CHECK( false == ( left == different ) );

        CHECK( false == ( left != left ) );
        CHECK( false == ( left != equal ) );
        CHECK( true == ( left != different ) );
      } // THEN
    } // WHEN
  } // GIVEN
} // SCENARIO

void verifyChunk( const thermal::IncoherentElasticAngularPdf& chunk ) {

  CHECK_THAT( -1., WithinRel( chunk.lowerCosineLimit() ) );
  CHECK_THAT(  1., WithinRel( chunk.upperCosineLimit() ) );
  CHECK_THAT( 1., WithinRel( chunk.incidentEnergy() ) );
  CHECK_THAT( 2.013538, WithinRel( chunk.debyeWallerIntegral() ) );

  CHECK_THAT( 1.280130036188690E-03, WithinRel( chunk( -1.0 ) ) );
  CHECK_THAT( 9.587878683533260E-03, WithinRel( chunk( -0.5 ) ) );
  CHECK_THAT( 7.181099970425270E-02, WithinRel( chunk(  0.  ) ) );
  CHECK_THAT( 5.378478231457790E-01, WithinRel( chunk(  0.5 ) ) );
  CHECK_THAT( 4.028356130036190E+00, WithinRel( chunk(  1.0 ) ) );

  // verifying test results for the integral and mean
  // njoy::scion::integration::AdaptiveGaussLobatto< double, double > integrator;
  // std::cout << std::setprecision( 15 ) << integrator( chunk, -1, 1, 1e-12 ) << std::endl;
  // auto mean = [&] ( double cosine ) { return cosine * chunk( cosine ); };
  // std::cout << std::setprecision( 15 ) << integrator( mean, -1, 1, 1e-12 ) << std::endl;

  // integral and mean value
  CHECK_THAT( 1., WithinRel( chunk.integral() ) );
  CHECK_THAT( 0.752316633727453, WithinRel( chunk.mean(), 5e-12 ) );

  // the lineariser has been tested a lot, results were generated by the test

  auto linear = chunk.linearise();
  CHECK( 129 == linear.numberPoints() );
  CHECK( 1 == linear.numberRegions() );
  CHECK( 129 == linear.cosines().size() );
  CHECK( 129 == linear.values().size() );
  CHECK( 1 == linear.boundaries().size() );
  CHECK( 1 == linear.interpolants().size() );
  CHECK( 128 == linear.boundaries()[0] );
  CHECK( InterpolationType::LinearLinear == linear.interpolants()[0] );
  CHECK_THAT( -1. , WithinRel( linear.cosines().front() ) );
  CHECK_THAT(  1. , WithinRel( linear.cosines().back() ) );
  CHECK_THAT( 1.280130036188690E-03, WithinRel( linear.values().front() ) );
  CHECK_THAT( 4.028356130036190E+00, WithinRel( linear.values().back() ) );
  CHECK( true == linear.isLinearised() );
}
